{
   "assignee" : null,
   "assignees" : [],
   "author_association" : "NONE",
   "body" : "When attempting to create a directory using \"/test_runner_Ã¢ÂÂ¿_Ã°ÂÂÂ_\", the following error is created.\r\n\r\n  `File \"test/functional/test_runner.py\", line 611, in <module>`\r\n  \t`    main()`\r\n`File \"test/functional/test_runner.py\", line 230, in main`\r\n  \t`    os.makedirs(tmpdir)`\r\n`File \"/usr/lib/python3.6/os.py\", line 220, in makedirs`\r\n\t`    mkdir(name, mode)` \r\n`UnicodeEncodeError: 'ascii' codec can't encode character '\\u20bf' in position 17: ordinal not in range(128)`\r\n\r\nSince, the code already checks for UTF-8 encoding/decoding at a previous place, it makes sense to check for this string too. \r\n\r\nI am using docker container for testing bitcoin and it comes with a default `sys.getfilesystemencoding() = ascii`, which is how I stumbled into this. \r\n\r\nIf this code will bloat the file, it might be better to use simple characters for directory name.",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 2,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/14237/comments",
   "created_at" : "2018-09-17T06:58:04Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/14237/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/14237",
   "id" : 360743371,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/14237/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "MDExOlB1bGxSZXF1ZXN0MjE1ODg3NTI0",
   "number" : 14237,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/14237.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/14237",
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/14237.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/14237"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "title" : "Fix for test runner UnicodeDecodeError when utf-8 is not supported",
   "updated_at" : "2018-09-17T16:40:30Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/14237",
   "user" : {
      "avatar_url" : "https://avatars2.githubusercontent.com/u/6881849?v=4",
      "events_url" : "https://api.github.com/users/sanket1729/events{/privacy}",
      "followers_url" : "https://api.github.com/users/sanket1729/followers",
      "following_url" : "https://api.github.com/users/sanket1729/following{/other_user}",
      "gists_url" : "https://api.github.com/users/sanket1729/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/sanket1729",
      "id" : 6881849,
      "login" : "sanket1729",
      "node_id" : "MDQ6VXNlcjY4ODE4NDk=",
      "organizations_url" : "https://api.github.com/users/sanket1729/orgs",
      "received_events_url" : "https://api.github.com/users/sanket1729/received_events",
      "repos_url" : "https://api.github.com/users/sanket1729/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/sanket1729/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/sanket1729/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/sanket1729"
   }
}
