[
   {
      "author_association" : "MEMBER",
      "body" : "I'm pretty sure this is an issue with Qt and newer versions of `make`. What version are you using here?",
      "created_at" : "2020-04-07T01:58:16Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/18536#issuecomment-610129581",
      "id" : 610129581,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/18536",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDYxMDEyOTU4MQ==",
      "updated_at" : "2020-04-07T01:58:16Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/610129581",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/863730?v=4",
         "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fanquake/followers",
         "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fanquake",
         "id" : 863730,
         "login" : "fanquake",
         "node_id" : "MDQ6VXNlcjg2MzczMA==",
         "organizations_url" : "https://api.github.com/users/fanquake/orgs",
         "received_events_url" : "https://api.github.com/users/fanquake/received_events",
         "repos_url" : "https://api.github.com/users/fanquake/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fanquake"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> I'm pretty sure this is an issue with Qt and newer versions of `make`. What version are you using here?\r\n\r\nQt is 5.9.8 as it is built in depends.\r\n\r\n```\r\n$ dpkg --status make | grep Version\r\nVersion: 4.1-9.1ubuntu1\r\n```\r\n\r\nIt seems nothing unusual...",
      "created_at" : "2020-04-07T09:44:46Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/18536#issuecomment-610287948",
      "id" : 610287948,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/18536",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDYxMDI4Nzk0OA==",
      "updated_at" : "2020-04-07T09:44:46Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/610287948",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/32963518?v=4",
         "events_url" : "https://api.github.com/users/hebasto/events{/privacy}",
         "followers_url" : "https://api.github.com/users/hebasto/followers",
         "following_url" : "https://api.github.com/users/hebasto/following{/other_user}",
         "gists_url" : "https://api.github.com/users/hebasto/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/hebasto",
         "id" : 32963518,
         "login" : "hebasto",
         "node_id" : "MDQ6VXNlcjMyOTYzNTE4",
         "organizations_url" : "https://api.github.com/users/hebasto/orgs",
         "received_events_url" : "https://api.github.com/users/hebasto/received_events",
         "repos_url" : "https://api.github.com/users/hebasto/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/hebasto/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/hebasto/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/hebasto"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "If you try and build with an older version of `make`, like 3.8x, I'm pretty certain it will work. I have seen this same failure before.",
      "created_at" : "2020-04-07T12:02:40Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/18536#issuecomment-610346398",
      "id" : 610346398,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/18536",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDYxMDM0NjM5OA==",
      "updated_at" : "2020-04-07T12:02:40Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/610346398",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/863730?v=4",
         "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fanquake/followers",
         "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fanquake",
         "id" : 863730,
         "login" : "fanquake",
         "node_id" : "MDQ6VXNlcjg2MzczMA==",
         "organizations_url" : "https://api.github.com/users/fanquake/orgs",
         "received_events_url" : "https://api.github.com/users/fanquake/received_events",
         "repos_url" : "https://api.github.com/users/fanquake/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fanquake"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> If you try and build with an older version of `make`, like 3.8x, I'm pretty certain it will work. I have seen this same failure before.\r\n\r\nBuilt and installed the old `make`:\r\n```\r\n$ make --version\r\nGNU Make 3.81\r\nCopyright (C) 2006  Free Software Foundation, Inc.\r\nThis is free software; see the source for copying conditions.\r\nThere is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A\r\nPARTICULAR PURPOSE.\r\n\r\nThis program built for armv7l-unknown-linux-gnu\r\n```\r\n\r\nbut it didn't help:\r\n```\r\n$ make qt -C depends\r\n...\r\nProject ERROR: Unknown module(s) in QT: xml\r\nmake: *** [/home/hebasto/bitcoin/depends/work/build/armv7l-unknown-linux-gnueabihf/qt/5.9.8-52a02fcd47f/qtbase/.stamp_configured] Error 3\r\nmake: Leaving directory `/home/hebasto/bitcoin/depends'\r\n```\r\n\r\nAnd the log does not mention `funcs.mk:251: ...` now.",
      "created_at" : "2020-04-08T17:53:30Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/18536#issuecomment-611101440",
      "id" : 611101440,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/18536",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDYxMTEwMTQ0MA==",
      "updated_at" : "2020-04-08T17:55:58Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/611101440",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/32963518?v=4",
         "events_url" : "https://api.github.com/users/hebasto/events{/privacy}",
         "followers_url" : "https://api.github.com/users/hebasto/followers",
         "following_url" : "https://api.github.com/users/hebasto/following{/other_user}",
         "gists_url" : "https://api.github.com/users/hebasto/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/hebasto",
         "id" : 32963518,
         "login" : "hebasto",
         "node_id" : "MDQ6VXNlcjMyOTYzNTE4",
         "organizations_url" : "https://api.github.com/users/hebasto/orgs",
         "received_events_url" : "https://api.github.com/users/hebasto/received_events",
         "repos_url" : "https://api.github.com/users/hebasto/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/hebasto/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/hebasto/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/hebasto"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Right, so I guess it's only on macOS where  using an older make fixes the issue. In any case, this seems like something that should be taken upstream to Qts bug tracker. I don't think we need an issue open for it here.",
      "created_at" : "2020-04-08T23:36:35Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/18536#issuecomment-611247718",
      "id" : 611247718,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/18536",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDYxMTI0NzcxOA==",
      "updated_at" : "2020-04-08T23:36:35Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/611247718",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/863730?v=4",
         "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fanquake/followers",
         "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fanquake",
         "id" : 863730,
         "login" : "fanquake",
         "node_id" : "MDQ6VXNlcjg2MzczMA==",
         "organizations_url" : "https://api.github.com/users/fanquake/orgs",
         "received_events_url" : "https://api.github.com/users/fanquake/received_events",
         "repos_url" : "https://api.github.com/users/fanquake/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fanquake"
      }
   }
]
