{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "The test is exercising the error, so it can capture it before the\r\ntest framework displays it on the console as an unforeseen\r\nfatal error.\r\n\r\nIt is odd to observe a fatal error after executing the complete\r\ntest suite and seeing it pass successfully.",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 1,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28050/comments",
   "created_at" : "2023-07-07T20:52:11Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28050/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/28050",
   "id" : 1794304701,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28050/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII585U9W7j",
   "number" : 28050,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/28050.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28050",
      "merged_at" : null,
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/28050.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28050"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28050/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28050/timeline",
   "title" : "test: make assumeUTXO test capture the expected fatal error",
   "updated_at" : "2023-07-07T21:27:11Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28050",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/5377650?v=4",
      "events_url" : "https://api.github.com/users/furszy/events{/privacy}",
      "followers_url" : "https://api.github.com/users/furszy/followers",
      "following_url" : "https://api.github.com/users/furszy/following{/other_user}",
      "gists_url" : "https://api.github.com/users/furszy/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/furszy",
      "id" : 5377650,
      "login" : "furszy",
      "node_id" : "MDQ6VXNlcjUzNzc2NTA=",
      "organizations_url" : "https://api.github.com/users/furszy/orgs",
      "received_events_url" : "https://api.github.com/users/furszy/received_events",
      "repos_url" : "https://api.github.com/users/furszy/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/furszy/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/furszy/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/furszy"
   }
}
