[
   {
      "author_association" : "NONE",
      "body" : "Note: I tried to locate the message \"ignoring getheaders from peer=0 because node is in initial block download\" emitted in [net_processing.cpp:3223] [ProcessMessage], but this is not what we have in the sources here. I see this message only in very old versions of Bitcoin sources.\r\n\r\nSo Bitcoin v23 was compiled from some sources that were out of sync (probably on another test branch, not meant to be part of the release).\r\n\r\nIt seems also that the test for seeing if some lock must be released is inverted (so this can explain the 100% CPU use seen on one CPU core by a thread runing the tight loop almost forever, of waiting for some exception or event which will come only when we shut down)",
      "created_at" : "2022-08-07T13:56:17Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207414185",
      "id" : 1207414185,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H962p",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207414185/reactions"
      },
      "updated_at" : "2022-08-07T14:00:22Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207414185",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "https://github.com/bitcoin/bitcoin/blob/v23.0/src/net_processing.cpp#L3223",
      "created_at" : "2022-08-07T13:59:52Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207414742",
      "id" : 1207414742,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H96_W",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207414742/reactions"
      },
      "updated_at" : "2022-08-07T13:59:52Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207414742",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "It seems that the way that ```LOCK(cs_main)``` are called is faulty, this is a real mess in a giant function containing many successive but exclusive if() that should be a switch to smaller functions. How are locks released when you return early without processing a message?",
      "created_at" : "2022-08-07T14:13:51Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207417692",
      "id" : 1207417692,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H97tc",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207417692/reactions"
      },
      "updated_at" : "2022-08-07T14:13:51Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207417692",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Anyway I do not understand why a node A in IBD (having for example here 300K blocks synchronized) that is connecting to a full node B (which is fully in sync with 760K blocks for now) and requests it a set of headers, gets these headers, but then node B needs to request headers to node A: how can a full node in sync request any headers (in the 760K blocks) to a node in IBD which does not have them, when node B ***knows*** that node A was just syncing (in the 300K blocks, several years behind)?\r\n\r\nNote that my node and the remote node were both using the v23 version of Bitcoin core... v23 seems to work OK only for a node that is already in sync (or not too far behind, so that a single headers request at most would allow them to know they are in sync). I've also seen in Bitcoin.io that v23 nodes seem now to be frequently stalling near the best tip. They apparently need to be regularly shut down and restarted to resync them.\r\n\r\nIn other words the logic for sync'ing nodes (even those that are not in IBD) is broken now in v23.",
      "created_at" : "2022-08-07T15:40:18Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207433696",
      "id" : 1207433696,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H9_ng",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207433696/reactions"
      },
      "updated_at" : "2022-08-07T15:44:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207433696",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Note also that even if downloading headers stalls (only advanced by about 1000 blocks at each run), the number of fully downloaded blocks NEVER progresses; all the available ones are already indexed, have their \"rev*dat\" file ready, the transaction indexi and coinbase indexes seem to progress (but only according to logs: in fact, some of them are merged to regenerate a new top index while the previous top index is deleted; there remains only indexes for the very old blocks); but according to statistics we are froen always to the same full block.\r\n\r\nI've enabled all documented \"check*\" options and validations, no probelm or corruption is ever detected.\r\nHave you tried to resync any FRESH full node recently (with no other data)?\r\nIs it likelty that some parts of full data for some blocks are ONLY available via Tor and not from any other node in the P2P network (via IPv4, IPVv6, or I2P), and not available even in so called \"full nodes\"? Or that I'm stuck in a dead branch of the network each time I try (note that my node is reachable via both IPv4 and IPv6, it uses UPnP for NAT over IPv4, but IPv6 is direct), and that my IPs are not reachable from some parts of the Internet, so that I need to use proxies?\r\n",
      "created_at" : "2022-08-07T17:12:33Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207448708",
      "id" : 1207448708,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H-DSE",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207448708/reactions"
      },
      "updated_at" : "2022-08-07T17:12:33Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207448708",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "After (too many) tests, I just figured out what to do: STOPPING using the QT UI for the IBD.\r\n\r\nYou may use te QT Interface just to start and try the configuration, but for the IBD it is unreliable.\r\n\r\nThis bug seems to be caused by Qt's own internal threads for its UI, adding it own unsynchronized locks or managing other condurrent threads used by Bitcoin incorrectly, or it could be a bug in the Qt integration inside the BitCoin Core UI.\r\n\r\nAlso I note that bitcointd is much faster than bitcoin-qt to progress in the IBD phase.\r\n\r\nOnce the IBD phase is complete. you can interrupt bitcoind (CTRL+C is safe, and it terminates much faster), if you want to continue with the QT UI (which will not consume a lot of CPU/disk/net resources). However I've noted frequently that the QT version can corrupt some indexes. The Qt integrationis not completely thread safe and has race isues.\r\n\r\nIMHO, the QT version should run the daemon only in a separate process (which could be registered in Windows as a standard \"service\", without any attached console), and control it with its RPC/IPC interface. Stopping the QT interface should not stop the daemon, unless we click a button to stop the daemon by its RPC/IPC interface (or via Windows services API).\r\n\r\nAs well there should be an option to send logs not in a flat file, but to Windows Events, where they could be compressed and managed automatically with a circular buffer (internally Windows Events will be packed in *.evtx or *.etl files and have a type handler managing common strings and formaters): this also saves a lot of I/O; Windows provides tools to dump these events into a flat file if needed, and to also filter them by sources, event type IDs, or sort them in different order. This would be mostly useful for log events generated by the daemon (debug logs for the QT interface can remain in flat files, or could be sent to a different source category in Windows Events).\r\n\r\n----\r\n\r\nNote also that I use a dedicated storage partition only for the /Bitcoin data files and NOT the main system partition.\r\n\r\nI have also formatted it not with the default cluster sizes (4KB) but increased it to clusters of 256KB (because most files are very large): this significantly improves the I/O, reduces the filesystem overhead in terms of I/O and memory for the filesystem structures (allocation bitmaps are smaller and modified much less often, because database files, undo files, index files, redo-logs, and debug log files are all allocated incrementally and in parallel), it improves the filesystem cache, reduces the fragmentation a lot (when the store is on harddisks, even on a fast array), so we also get reduced latency.\r\n\r\nThis also greatly facilitates maintenance.",
      "created_at" : "2022-08-07T20:08:17Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207476578",
      "id" : 1207476578,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H-KFi",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207476578/reactions"
      },
      "updated_at" : "2022-08-07T20:25:16Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207476578",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Permanent solution is to downgrade to 22.0",
      "created_at" : "2022-08-07T21:09:01Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207485817",
      "id" : 1207485817,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H-MV5",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207485817/reactions"
      },
      "updated_at" : "2022-08-07T21:12:10Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207485817",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/98498676?v=4",
         "events_url" : "https://api.github.com/users/memz13155n/events{/privacy}",
         "followers_url" : "https://api.github.com/users/memz13155n/followers",
         "following_url" : "https://api.github.com/users/memz13155n/following{/other_user}",
         "gists_url" : "https://api.github.com/users/memz13155n/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/memz13155n",
         "id" : 98498676,
         "login" : "memz13155n",
         "node_id" : "U_kgDOBd74dA",
         "organizations_url" : "https://api.github.com/users/memz13155n/orgs",
         "received_events_url" : "https://api.github.com/users/memz13155n/received_events",
         "repos_url" : "https://api.github.com/users/memz13155n/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/memz13155n/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/memz13155n/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/memz13155n"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "No, version 22.0 has the same issue (though it does not have the bug present in the EXE installer for Windows caused by ASLR, due to a bug in MAKENSIS which creates an invalid EXE by when it appends the \"pcode\" compiled from the nsis.ini script, and then appends the compressed files, because it does not correctly manages the relations that are placed after them, but forgets to update the PE EXE header to the new placement of the relocation section in the EXE file)\r\n\r\nv22 tools has the same issue with the IBD which stalls as well if you use the QT interface (in addition, the bitcoin-qt.exe also corrupts the indexes; Qt is unsafe as it silently changes some global settings in the C runtime environment, and the LevelDB is also affected; it seems that Qt temporarily changes the current working directory, and files accessed by LeevlDB do not seem to specify the absolute path, so there are race conditions where some Qt threads may affect concurrent LevelDB threads.\r\n\r\nIF you use only the CLI daemon (v22 or v23), there's no such conflict and race conditions; it is faster in both cases than their QT version; but the v23 includes many fixes (multiple ones being critical) still not present in the v22 binaries (and not backported in the v22 sources).\r\n\r\nI just hope that a new v23 will be recreated soon (and there are other bugs pending to be solved, already present in the sources, but not in the precompiled binaries).\r\n\r\nIn my opinon the QT version of the daemon has not been seriously tested. And trying to link the daemon with the QT interface is an error; the QT interface should spawn or control the regular CLI daemon",
      "created_at" : "2022-08-07T23:58:35Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1207512664",
      "id" : 1207512664,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585H-S5Y",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207512664/reactions"
      },
      "updated_at" : "2022-08-07T23:58:35Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1207512664",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Learning from this, just use the CLI version of bitcoin core by running bitcoind.exe on cmd and have another cmd session to interface with the wallet using another executable (I think it is bitcoin-cli.exe)",
      "created_at" : "2022-08-08T18:15:50Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1208452260",
      "id" : 1208452260,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IB4Sk",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1208452260/reactions"
      },
      "updated_at" : "2022-08-08T18:16:15Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1208452260",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/98498676?v=4",
         "events_url" : "https://api.github.com/users/memz13155n/events{/privacy}",
         "followers_url" : "https://api.github.com/users/memz13155n/followers",
         "following_url" : "https://api.github.com/users/memz13155n/following{/other_user}",
         "gists_url" : "https://api.github.com/users/memz13155n/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/memz13155n",
         "id" : 98498676,
         "login" : "memz13155n",
         "node_id" : "U_kgDOBd74dA",
         "organizations_url" : "https://api.github.com/users/memz13155n/orgs",
         "received_events_url" : "https://api.github.com/users/memz13155n/received_events",
         "repos_url" : "https://api.github.com/users/memz13155n/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/memz13155n/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/memz13155n/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/memz13155n"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Also I've discovered that in some cases, during the IBD phase, if we have too many open connections with other peers, we exhaust the maximum number of allowed open files in the whole process.\r\nAs a result we get a status saying \"Error: Error reading from database, shutting down.\"\r\n\r\nBut what is worse is that during that shutdown, Bitcoind or Bitcoin-qt is unable to save its current indexing: it should first close all peer connections, make sure that they don't have threads open in existing LevelDB files or on block files, BEFORE finally saving the indexing state. This occurs much more often with the QT version probably beaue Qt itself uses many additional file handles.\r\n\r\nSo Bitcoin core is not properly handling cases where it cannot open files. If this occurs, an exception handler should first seek to terminate connections to peers with lower priority (notably incoming peers before outgoing peers).\r\n\r\nAs well there are visibly leaks of open file handles if we leave Bitcoin Core open for a long time, especially during the IBD phase. The work around for that is to run the IBD phase for a limited time (e.g. stop after half an hour). Bitcoin core should in fact make such cleanup, possibly closing all connections to peers regularly, flushing its indexing state.\r\n\r\nAs well it should NOT cleanup all files in the chainstate immediately, but should preserve at least the previous valid manifest and its attached lbd files. If ever there's been a corruption because it could not save the last chainstate, at least it has a way to restart from the previous manifest, and may be me more conservative by limiting the number of peers with which it interacts (for now there's no limit at all, and during the IBD, remote peers can request any data from anywhere, in any order, and this locks too many files, more that what is allowed in the configuration.\r\n\r\nBy default it accepts up to 125 peers, and about 2000 open files, but during the IBD and if you have multiple indexes in construction, that limit is easily exhausted (notably when you run it over a Gigabit  Internet connection): you cannot safely run the IBD phase and at the same time allow the construction of several additional indexes in parallel (e.g. with blockfilterindex=1, coinstatsindex=1, peerblockfilters=1, peerbloomfilters=1: you can only enable them one by one, after you'ev succesfully finished the IBD and each of the following phases for other indexes).\r\n\r\nSuch forced shutdown (which incorrectly states that the \"blocks are corrupted\", when in fact it could not even open them because of internal resource limits) leaving the chainstate after the shutdown in an inconsistant state (I've checked the blocks they were perfectly correct, it's just that Bitcoin Core could not open them!) and it is very harmful (because we've lost the chainstate which becomes unrecoverable and has to be reindexed once again from the begining) and as opposed to what is said, this has nothing to do with a hardware problem on the sorage or with the memory: it is architectural in the app, which does not use safe management of its own resources usage, even if the host can perfectly support more! The so called \"corruption\" is generated by Bitcoin Core itself by not properly tracking its own internal errors for its own resource usages, whose given diagnostics are wrong about their effective cause).\r\n\r\nAlso I wonder why, with the option \"reindex-chainstate\", Bitcoin core will not just run without accepting ANY incoming connections; it may just open 1 outgoing connection to a full peer, and it should be sufficient for the time needed to recover the chainstate to the last block.",
      "created_at" : "2022-08-11T07:38:08Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211647918",
      "id" : 1211647918,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IOEeu",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211647918/reactions"
      },
      "updated_at" : "2022-08-11T07:42:42Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211647918",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "another proof that the logic for IBD is wrong and stalls after one of many retries without any success:\r\n\r\n```\r\n2022-08-11T12:10:31Z init message: Loading block indexâ¦\r\n2022-08-11T12:10:31Z Switching active chainstate to Chainstate [ibd] @ height -1 (null)\r\n2022-08-11T12:10:31Z Opening LevelDB in G:\\Bitcoin\\blocks\\index\r\n2022-08-11T12:10:31Z Opened LevelDB successfully\r\n2022-08-11T12:10:31Z Using obfuscation key for G:\\Bitcoin\\blocks\\index: 0000000000000000\r\n2022-08-11T12:10:35Z LoadBlockIndexDB: last block file = 2611\r\n2022-08-11T12:10:35Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=12, size=15108850, heights=686224...686609, time=2021-06-04...2021-06-07)\r\n2022-08-11T12:10:35Z Checking all blk files are present...\r\n2022-08-11T12:10:36Z Opening LevelDB in G:\\Bitcoin\\chainstate\r\n2022-08-11T12:10:36Z Opened LevelDB successfully\r\n2022-08-11T12:10:36Z Using obfuscation key for G:\\Bitcoin\\chainstate: ea53eab331512c62\r\n2022-08-11T12:10:36Z Loaded best chain: hashBestChain=00000000000000003a8d7be745e0515c78b51014311f20235327855bdd1e87e4 height=277116 date=2013-12-26T21:18:12Z progress=0.039674\r\n2022-08-11T12:10:36Z init message: Verifying blocksâ¦\r\n2022-08-11T12:10:36Z Verifying last 6 blocks at level 3\r\n2022-08-11T12:10:36Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].\r\n2022-08-11T12:10:36Z No coin database inconsistencies in last 6 blocks (2745 transactions)\r\n2022-08-11T12:10:36Z  block index            5193ms\r\n2022-08-11T12:10:36Z block tree size = 748958\r\n2022-08-11T12:10:36Z nBestHeight = 277116\r\n2022-08-11T12:10:36Z loadblk thread start\r\n2022-08-11T12:10:36Z Imported mempool transactions from disk: 0 succeeded, 0 failed, 0 expired, 0 already there, 0 waiting for initial broadcast\r\n2022-08-11T12:10:36Z loadblk thread exit\r\n2022-08-11T12:10:36Z torcontrol thread start\r\n2022-08-11T12:10:36Z AddLocal([2a01:e0a:30:2b70::4925:5939]:8333,1)\r\n2022-08-11T12:10:36Z Discover: JUPITER - 2a01:e0a:30:2b70::4925:5939\r\n2022-08-11T12:10:36Z Bound to 127.0.0.1:8334\r\n2022-08-11T12:10:36Z Bound to [::]:8333\r\n2022-08-11T12:10:36Z Bound to 0.0.0.0:8333\r\n2022-08-11T12:10:36Z Loaded 2 addresses from \"anchors.dat\"\r\n2022-08-11T12:10:36Z 2 block-relay-only anchors will be tried for connections.\r\n2022-08-11T12:10:36Z init message: Starting network threadsâ¦\r\n2022-08-11T12:10:36Z net thread start\r\n2022-08-11T12:10:36Z dnsseed thread start\r\n2022-08-11T12:10:36Z Waiting 300 seconds before querying DNS seeds.\r\n2022-08-11T12:10:36Z addcon thread start\r\n2022-08-11T12:10:36Z opencon thread start\r\n2022-08-11T12:10:36Z init message: Done loading\r\n2022-08-11T12:10:36Z msghand thread start\r\n2022-08-11T12:10:37Z New outbound peer connected: version: 70016, blocks=748973, peer=0 (block-relay-only)\r\n2022-08-11T12:10:37Z New outbound peer connected: version: 70016, blocks=748973, peer=1 (block-relay-only)\r\n2022-08-11T12:10:49Z New outbound peer connected: version: 70016, blocks=748973, peer=2 (outbound-full-relay)\r\n2022-08-11T12:10:55Z New outbound peer connected: version: 70016, blocks=748973, peer=3 (outbound-full-relay)\r\n2022-08-11T12:10:56Z New outbound peer connected: version: 70016, blocks=748973, peer=4 (outbound-full-relay)\r\n2022-08-11T12:10:56Z New outbound peer connected: version: 70016, blocks=748973, peer=5 (outbound-full-relay)\r\n2022-08-11T12:11:04Z New outbound peer connected: version: 70016, blocks=748973, peer=6 (outbound-full-relay)\r\n2022-08-11T12:11:10Z New outbound peer connected: version: 70016, blocks=748973, peer=7 (outbound-full-relay)\r\n2022-08-11T12:11:11Z New outbound peer connected: version: 70015, blocks=748973, peer=8 (outbound-full-relay)\r\n2022-08-11T12:11:11Z New outbound peer connected: version: 70015, blocks=748973, peer=9 (outbound-full-relay)\r\n2022-08-11T12:11:17Z New outbound peer connected: version: 70016, blocks=748973, peer=10 (outbound-full-relay)\r\n2022-08-11T12:11:29Z New outbound peer connected: version: 70015, blocks=748972, peer=13 (outbound-full-relay)\r\n```\r\n\r\nAnd here it stalls at nBestHeight = 277116 (still in Chainstate [ibd] @ height -1 (null)), even though it knows at startup that block tree size = 748958, and then makes outgoing connection to peers all having blocks=748973, without asking anything else to them (those peers disconnect, and the local node just continues to make outbound connections). The local node already has all blocks up to height=748958, but stops going further and noes not index them. What is it waiting for?\r\n\r\nHow many times I've tried to relaunch the daemon with -reindex-chainstate? The chainstate management is definitely broken with bad assumptions, also causing frequent crashes when it does not just stall!",
      "created_at" : "2022-08-11T12:19:02Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211913053",
      "id" : 1211913053,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPFNd",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211913053/reactions"
      },
      "updated_at" : "2022-08-11T12:22:58Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211913053",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "What does the `getchaintips` RPC output?",
      "created_at" : "2022-08-11T12:22:02Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211916045",
      "id" : 1211916045,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPF8N",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211916045/reactions"
      },
      "updated_at" : "2022-08-11T12:22:02Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211916045",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Bitcoin> bitcoin-cli.exe -getinfo\r\nChain: main\r\nBlocks: 277116\r\nHeaders: 277116\r\nVerification progress: âââââââââââââââââââââ 3.9674%\r\nDifficulty: 1180923195.258026\r\n\r\nNetwork: in 0, out 0, total 0\r\nVersion: 230000\r\nTime offset (s): 0\r\nProxies: n/a\r\nMin tx relay fee rate (BTC/kvB): 0.00001000\r\n\r\n(this is when it stalls, only the \"Network: in 0, out 0, total 0\" line changes with the number of peers connected and disconnecting continuously)\r\n\r\nI can press CTRL+C, the daamon will exit normally without error, and I can relauch it, nothing changes. the chaintips never changes, and it is never updated even when I activate the option \"-debug=all\" to get more logs.\r\n\r\nI can use v22 or v23 (only from the published releases, I did not compile them) I get the same.\r\n\r\nMore details with \"debug=all\":\r\n\r\n```\r\n2022-08-11T12:35:30Z received: getheaders (1029 bytes) peer=45\r\n2022-08-11T12:35:30Z Ignoring getheaders from peer=45 because node is in initial block download\r\n2022-08-11T12:35:31Z received: pong (8 bytes) peer=45\r\n2022-08-11T12:35:32Z socket closed for peer=31\r\n2022-08-11T12:35:32Z disconnecting peer=31\r\n2022-08-11T12:35:32Z Cleared nodestate for peer=31\r\n2022-08-11T12:35:32Z initial getheaders (277115) to peer=41 (startheight:748977)\r\n2022-08-11T12:35:32Z sending getheaders (997 bytes) peer=41\r\n2022-08-11T12:35:32Z Selected 2.61.65.59:8333 from new\r\n2022-08-11T12:35:32Z trying connection 2.61.65.59:8333 lastseen=49.3hrs\r\n2022-08-11T12:35:32Z sending addr (31 bytes) peer=38\r\n2022-08-11T12:35:32Z received: headers (162003 bytes) peer=41\r\n2022-08-11T12:35:32Z AcceptBlockHeader: block 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b is marked invalid\r\n2022-08-11T12:35:32Z Misbehaving: peer=41 (0 -> 100) DISCOURAGE THRESHOLD EXCEEDED: invalid header received\r\n2022-08-11T12:35:32Z Disconnecting and discouraging peer 41!\r\n2022-08-11T12:35:32Z disconnect by subnet matched peer=41; disconnecting\r\n2022-08-11T12:35:32Z disconnecting peer=41\r\n2022-08-11T12:35:32Z Cleared nodestate for peer=41\r\n2022-08-11T12:35:32Z initial getheaders (277115) to peer=36 (startheight:748977)\r\n2022-08-11T12:35:32Z sending getheaders (997 bytes) peer=36\r\n2022-08-11T12:35:33Z received: headers (162003 bytes) peer=36\r\n2022-08-11T12:35:33Z AcceptBlockHeader: block 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b is marked invalid\r\n2022-08-11T12:35:33Z Misbehaving: peer=36 (0 -> 100) DISCOURAGE THRESHOLD EXCEEDED: invalid header received\r\n2022-08-11T12:35:33Z Disconnecting and discouraging peer 36!\r\n2022-08-11T12:35:33Z disconnect by subnet matched peer=36; disconnecting\r\n2022-08-11T12:35:33Z disconnecting peer=36\r\n2022-08-11T12:35:33Z Cleared nodestate for peer=36\r\n2022-08-11T12:35:33Z initial getheaders (277115) to peer=34 (startheight:748977)\r\n2022-08-11T12:35:33Z sending getheaders (997 bytes) peer=34\r\n2022-08-11T12:35:33Z received: headers (162003 bytes) peer=34\r\n2022-08-11T12:35:33Z AcceptBlockHeader: block 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b is marked invalid\r\n2022-08-11T12:35:33Z Misbehaving: peer=34 (0 -> 100) DISCOURAGE THRESHOLD EXCEEDED: invalid header received\r\n2022-08-11T12:35:33Z Disconnecting and discouraging peer 34!\r\n2022-08-11T12:35:33Z disconnect by subnet matched peer=34; disconnecting\r\n2022-08-11T12:35:33Z disconnecting peer=34\r\n2022-08-11T12:35:33Z Cleared nodestate for peer=34\r\n2022-08-11T12:35:33Z initial getheaders (277115) to peer=33 (startheight:748977)\r\n2022-08-11T12:35:33Z sending getheaders (997 bytes) peer=33\r\n2022-08-11T12:35:33Z received: headers (162003 bytes) peer=33\r\n2022-08-11T12:35:33Z AcceptBlockHeader: block 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b is marked invalid\r\n2022-08-11T12:35:33Z Misbehaving: peer=33 (0 -> 100) DISCOURAGE THRESHOLD EXCEEDED: invalid header received\r\n2022-08-11T12:35:33Z Disconnecting and discouraging peer 33!\r\n2022-08-11T12:35:33Z disconnect by subnet matched peer=33; disconnecting\r\n2022-08-11T12:35:33Z disconnecting peer=33\r\n2022-08-11T12:35:33Z Cleared nodestate for peer=33\r\n2022-08-11T12:35:33Z initial getheaders (277115) to peer=38 (startheight:748971)\r\n2022-08-11T12:35:33Z sending getheaders (997 bytes) peer=38\r\n2022-08-11T12:35:34Z received: inv (397 bytes) peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 44fd2ca0a4e5554690cd35871cf9da6a122c247b070504525351582fa1c7de37  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 29d1039191288ff05646be90af2236f7e3161365dc5857980f3a8189c9c5754a  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 254600576b8891f6389bae1151ef3b72ee8c8d1a2f633165a069705e60ccc694  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 19c968d92c93c5a9f6c25220762f9d41c4b6dec83ab70b724668c3a6536c0773  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 3f9fe1d48bac7d20fc33e688f18667473b959739716c436b0f5479ee7bf7a346  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 288ff0886891bae9fa1471db7c7a909f3b3ec015e3ca0f407b32889eb44ea259  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 3aba4502674f4c46de3b2916647793f081aebc31b134d700d4ab8d798d2b1b6d  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 1239b7f6ff54ab12c7b1d5730d7a2ea4a827e559d3e8461ccee06ab58ac7e470  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 2b13fe8c8e41401a5c17b6d241cde283cee18b974ed7379dfa3b46f1e435979b  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx 16bfe62a3e9d8fd2c8f8e93086e73218a4de9a38eb77c4893e66b9ef5ea4c106  new peer=35\r\n2022-08-11T12:35:34Z got inv: wtx abc6b8fd20904a859715114cda786af8ce6f58ab1286f9be14eb457ba38b8558  new peer=35\r\n2022-08-11T12:35:37Z connection attempt to 2.61.65.59:8333 timed out\r\n```\r\n\r\nDo I always find only \"misbehaving\" nodes? Or isn't Bitcoin Core v22+ itself misbehaving?\r\n\r\nNote that I have stopped since long trying to use the QT version (which bugs too much often). I just use the command line daemon (bitcoind) and the command line CLI query client (bitcoin-cli). In all cases these stalls or crashes are inside the management of the chainstate (there's no corruption at all in the downloaded blocks) occuring at random position (with the same valid blocks downloaded I can restart \"reindex-chainstate\", it always fails.\r\n\r\nIf I restart with \"reindex\" it forces downloading again the whole blocks, but when performing binary compares with a backup of blocks from previous runs, they are strictly identical (except \"block00000.dat\" which is special and contains the current root of the tree, updated at each run).\r\n\r\nI thought my PC was too fast, and my Gigabit figer internet too fast. I tried running the daemon in a Linux VM, by restricting its amount of memory and network bandwidth allocated in the hypervisor. Still I get the same results: It's never possible to terminate the IBD, I always get crashes by corruptions in the chainstate (some *.ldb files were deleted too early after a merge, even though they were still needed for other upper *.ldb files files; or I got the chainstate stalled as well in the IBD, and no corruption detected by the daemon).\r\n\r\nI don't know what kind of machine or specific configuration can really make Bitcoin Core working and succeed in their IBD phase.\r\n\r\nOr the Bitcoin chain already and really contains invalid blocks (that were rejected much longer after they were first accepted), that can't be eliminated and no progress is possible (in that case it is the whole shared Bitcoin chain which is damaged since long, or Bitcoin Core has forgotten to implement a rule to perform a safe cleanup of rejected blocks).\r\n\r\nAre there reliable Bitnode softwares **other than Bitnode Core v22+** that can be used today to run a full node with the current state of the chain?",
      "created_at" : "2022-08-11T12:23:55Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211918071",
      "id" : 1211918071,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPGb3",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211918071/reactions"
      },
      "updated_at" : "2022-08-11T13:06:08Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211918071",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "And if you still think that my machine has a hardware problem, I've also tried on different PCs, and with a Linux VM hosted in Azure and Amazon. They are also failing to sync the IBD with the same symptoms in the \"chainstate\" (corruption of the chain with index *.lbd files deleted too soon, and missing, or stalling at unpredictable height).\r\n\r\nI think that those that have Bitcoin Core working on their machine had to compile it themselves. But they DO NOT use your signed binary releases (which aer most prbably not compiled correctly in a safe environment; I know you use a new build chain in \"GUIX\", but it is then not working at all: do you really test the generated binaries, which seem to be broken locally in GUIX by some unknown and unsafe/untested local customizations and patches, or running on a broken/damaged Linux installation?).\r\n\r\nMy opinion is that it is not my machines that are borken, but your \"GUIX\" environment used to produce the signed binaries. And unfortunately you've not opensourced that environment; may be you should retry by using an hypervisor like Proxmox and building a \"template\" for a safe Linux image, a safe installtion of GCC and related tools; that tempalte would then be easy to replicate when you want to make all your tests before actual releases. The sources of Bitcoin Core alone is definitely not sufficient without a safe build chain we can replicate easily. Apparently you are only testing Bitcoin core with binaries you compile on your local machines without using \"GUIX\", you never use or test the **released** signed binaries published on your official website!",
      "created_at" : "2022-08-11T13:12:02Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211970713",
      "id" : 1211970713,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPTSZ",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211970713/reactions"
      },
      "updated_at" : "2022-08-11T13:25:35Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211970713",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Can you report the output of `getchaintips`?",
      "created_at" : "2022-08-11T13:13:38Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1211972752",
      "id" : 1211972752,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPTyQ",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211972752/reactions"
      },
      "updated_at" : "2022-08-11T13:13:38Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1211972752",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "```\r\nbitcoin> bitcoin-cli getchaintips\r\n[\r\n  {\r\n    \"height\": 748957,\r\n    \"hash\": \"00000000000000000002997b7cf13fed750e2183d7693a24785c9f594389ee88\",\r\n    \"branchlen\": 471841,\r\n    \"status\": \"invalid\"\r\n  },\r\n  {\r\n    \"height\": 277116,\r\n    \"hash\": \"00000000000000003a8d7be745e0515c78b51014311f20235327855bdd1e87e4\",\r\n    \"branchlen\": 0,\r\n    \"status\": \"active\"\r\n  }\r\n]\r\n```\r\n\r\nDo I need to manually delete some recent blk0*.dat and rev0*.dat and restart indexing again and again? Are they caused by misbehaving nodes (or malwares) in the P2P network distributing wrong blocks and causing normal nodes in IBD to fail or stall? Is it the signal of an DoS attack again the Bitcoin chain in order to take control of it by \"ejecting\" regular nodes with such bad blocks? In that case, they are succesful in their attacks since many months! I've never been able to compleet the IBD from any machine when using Bitcoin Core. May be this is the sign that Bitcoin Core does not fully apply the \"consensus\" rules for validating new blocks, and that it accepts them too early, and is unable to rollback safely when they are detected as \"disapproved\" too much longer later. And above some limits (a big number of bad block in the chain to revert to replace one that came much earlier in the chain), it seems to crash and corrupt the \"chainstate\" index files itself.\r\n\r\nBut may be there are other competing softwares that could work such as https://www.bitcoinabc.org/ (if they've detected such attack and are able to isolate and fix it)?\r\n",
      "created_at" : "2022-08-11T13:56:44Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212025604",
      "id" : 1212025604,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPgsE",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212025604/reactions"
      },
      "updated_at" : "2022-08-11T14:12:59Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212025604",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "So, for whatever reason, your node has marked block 277117 (0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b) incorrectly as invalid. It's not synchronizing further, because it is treating every peer that hands it block 277177 as malicious. We'll need to figure out why that is happening. Your comment above about running out of file descriptors seems like a useful lead.\r\n\r\nFirst, we need to know if it is the block on disk itself that is corrupted, or the validation database. It's likely the latter, but to find out, run `reconsiderblock 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b`, and report what you see in debug.log at that time.\r\n\r\n> Do I need to manually delete some recent blk0*.dat and rev0*.dat and restart indexing again and again?\r\n\r\nIf the blocks themselves are corrupted, you'll need to use `-reindex`. If it's just the database that is corrupted, `-reindex-chainstate` should suffice. Given that it sounds like you've tried the latter several times and that doesn't help, it's either a problem with the blocks themselves, or somehow your Bitcoin Core instance is corrupting itself time after time. Looking at the `reconsiderblock` output will help figure this out.\r\n\r\n> Are they caused by misbehaving nodes (or malwares) in the P2P network distributing wrong blocks and causing normal nodes in IBD to fail or stall?\r\n\r\nMisbehaving nodes should never be able to cause Bitcoin Core to incorrectly mark a block as invalid, so no.\r\n\r\n> May be this is the sign that Bitcoin Core does not fully apply the \"consensus\" rules for validating new blocks, and that it accepts them too early\r\n\r\nNo.\r\n\r\n> But may be there are other competing softwares that could work such as https://www.bitcoinabc.org/ (if they've detected such attack and are able to isolate and fix it)?\r\n\r\nThat software is for a different currency, with different consensus rules. It will not synchronize with the Bitcoin network/chain/currency.",
      "created_at" : "2022-08-11T14:12:00Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212044042",
      "id" : 1212044042,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPlMK",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 1,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 1,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212044042/reactions"
      },
      "updated_at" : "2022-08-11T14:13:27Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212044042",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I jsut ran \"bitcoin-cli reconsiderblock 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b\".\r\n\r\nAnd instantly the daemon restarts the IBD synchronization.\r\n\r\nI see many \"UpdateTip: new best=*\" logged.\r\n\r\nI did not have to use \"-reindex\" or \"-reindex-chainstate\".",
      "created_at" : "2022-08-11T14:15:20Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212048271",
      "id" : 1212048271,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPmOP",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212048271/reactions"
      },
      "updated_at" : "2022-08-11T14:16:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212048271",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> I see many \"UpdateTip: new best=*\" logged.\r\n\r\nYou'll need to provide the exact debug log at the exact location when the RPC `reconsiderblock` was called",
      "created_at" : "2022-08-11T14:18:05Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212051539",
      "id" : 1212051539,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPnBT",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212051539/reactions"
      },
      "updated_at" : "2022-08-11T14:18:05Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212051539",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "@verdy-p Do the heights keep going up, past 277117? If so, it sounds like there may not actually have been any corruption at all, but just a one-off validation issue.\r\n",
      "created_at" : "2022-08-11T14:19:36Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212053658",
      "id" : 1212053658,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPnia",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212053658/reactions"
      },
      "updated_at" : "2022-08-11T14:19:36Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212053658",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Too late... that log has been \"autocleared\" with the huge amiunt of \"UpdateTip: new best=*\" that instantly started (and I cannot recover it as well fro mthe console which has flushed it as well from its memory.\r\n\r\nYes \"bitcoin-cli getinfo\" shows that it is progressing again, as well as \"bitcoin-cli getchaintips\".\r\n\r\nNote that in the separate console where I ran \"bitcoin-cli reconsiderblock 0000000000000002cdf7bce4c09c0849f789a9508d812d3ca430429f6213688b\", the command never exited; I had to press CTRL+C to terminate the RPC session. But this does not affect the daemon which continues at fast speed.\r\n\r\nFor example I get now:\r\n````\r\nbitcoin> bitcoin-cli getchaintips\r\n[\r\n  {\r\n    \"height\": 748989,\r\n    \"hash\": \"000000000000000000081ba73135ef39612f940bc77e76240e52ef83b5f0b1e9\",\r\n    \"branchlen\": 443985,\r\n    \"status\": \"headers-only\"\r\n  },\r\n  {\r\n    \"height\": 305004,\r\n    \"hash\": \"0000000000000000162865e084d637f7e7fbd3580a2dae91abe6d47fa4ef8abe\",\r\n    \"branchlen\": 0,\r\n    \"status\": \"active\"\r\n  }\r\n]\r\n```\r\n",
      "created_at" : "2022-08-11T14:19:48Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212053928",
      "id" : 1212053928,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPnmo",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212053928/reactions"
      },
      "updated_at" : "2022-08-11T14:24:34Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212053928",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "@verdy-p Yeah, it's expected that it doesn't exit; it'll exit whenever it is done reconsidering that block, and all other blocks whose validation is triggered by it. If all goes well, that won't be until it reaches the tip of the downloaded blocks you had before (height 748957) - or until somehow another incorrect validation error occurs.",
      "created_at" : "2022-08-11T14:24:50Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212060311",
      "id" : 1212060311,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPpKX",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212060311/reactions"
      },
      "updated_at" : "2022-08-11T14:24:50Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212060311",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Could it be caused by some OS limitation (temporarily disabling write accesses for some critical operations, and sending a \"busy\" status error that Bitcoin Core does not corerctly interpret, and cannot recover just by a retry after some reasonnable delay; e.g. it could be generated by security tools, instructing a running app to \"pause\" temporarily and not allowing for example to create or delete new files in the directory containing files of the chainstate, which changes really too fast with thousands files added/deleted each minute)? It may be caused by the fact that even if we close a file handle, the OS may still maintain it internally for its own operations, and cannot allocate new file handles for some time, until the OS performs some background cleanup in the background with the filesystem.\r\n\r\nSo the issue would be that Bitcoin core fails while trying to open a new file: the OS does not accept immediately to give it a new file handle, and the error returned may indicate that the application needs to wait a bit before retrying.",
      "created_at" : "2022-08-11T14:31:26Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212070234",
      "id" : 1212070234,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPrla",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212070234/reactions"
      },
      "updated_at" : "2022-08-11T14:36:59Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212070234",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "@verdy-p That sounds like a possibility.\r\n\r\nIf so, I would guess that whatever is going on is likely happening when Bitcoin Core is flushing the chainstate database to disk. You can trigger such a flush manually by calling `gettxoutsetinfo`, if you'd like.",
      "created_at" : "2022-08-11T14:33:38Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212073126",
      "id" : 1212073126,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPsSm",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212073126/reactions"
      },
      "updated_at" : "2022-08-11T14:33:38Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212073126",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Thanks for the tip about \"bitcoin-cli gettxoutsetinfo\". It takes some minutes to complete until it returns:\r\n```\r\n{\r\n  \"height\": 347551,\r\n  \"bestblock\": \"000000000000000014f5db2548b27a532ba2d81e22ada3800e787383496da281\",\r\n  \"txouts\": 17634623,\r\n  \"bogosize\": 1340919614,\r\n  \"hash_serialized_2\": \"7a9209a30d15eade5e74248095962d82d67c1b060e91f9eb7127eac805aafbb0\",\r\n  \"total_amount\": 13938639.77152479,\r\n  \"transactions\": 4995854,\r\n  \"disk_size\": 950709316\r\n}\r\n```\r\nBut this does not seem to stop the daemon which continues adding new tips at increadible rate (I just see instantly the truncation of some \"level-0\" table for less than one second, then it continues indexing at fast rate. I get the reply from \"gettxoutsetinfo\" only a few minutes later (probably the RPC service thread has low priority to reply, most of the CPU threads are for the indexing).",
      "created_at" : "2022-08-11T14:41:14Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212082213",
      "id" : 1212082213,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPugl",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212082213/reactions"
      },
      "updated_at" : "2022-08-11T14:41:14Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212082213",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "So for some reasons if the OS returns some error when opening a file, the log should detail that error (with the exact error number: it is very likely non-fatal, we should just retry after waiting a couple of seconds: there does not seem to exist any exception handler to handle this case), instead of just saying that it can't open a file and give a false guess about a corruption and exiting abruptly (and at that time, trying to flush the state of the chain before exising will also faile for the same reason, as it will need to open many files for that: at that time this crashes, and we are unable to recover with missing files).",
      "created_at" : "2022-08-11T14:46:07Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212088139",
      "id" : 1212088139,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPv9L",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212088139/reactions"
      },
      "updated_at" : "2022-08-11T14:47:44Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212088139",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "@verdy-p If that's the issue, it's a bug inside LevelDB, which we'll be unlikely to fix on our own. At this point I would avoid jumping to any conclusions and just try to reproduce the problem so we can try things.",
      "created_at" : "2022-08-11T14:47:55Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212091150",
      "id" : 1212091150,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPwsO",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212091150/reactions"
      },
      "updated_at" : "2022-08-11T14:47:55Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212091150",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "It's true that I've never seen any LevelDB application creating and deleting so many indexes at such incredible rate. Generally these indexes are quite stable, they just grow slowly in size.\r\nMay be the maximum index sizes for each table is too small (2MB) for a fast machine, and we easily reach the limitation of the OS for the filesystem background operations that are likely starting as soon as we close the file (and LevelDB doesnot seem to \"sync\" the filesystem when it closes a file, it allwos the OS to perform background cleanup, but the file handle remains allocated for the process as long as the OS has not terminated those operations.\r\n\r\nDoes LevelDB uses some optimized operations that allow file close to return instantly without waiting the effective completion? such optimization does not seem to be very \"safe\". The \"close()\" operation (or delete/move/rename operation) should be blocking.\r\n\r\nBut visibly LevelDB seems to use worker threads to complete its file I/O like ni this project (using the Go language)\r\n\r\nhttps://github.com/syndtr/goleveldb/blob/master/leveldb/storage/file_storage.go\r\n\r\nLevelDB creates an increadible amount of threads if I monitor Bitcoin Core and just look at them, and the total number of file handles that are open (they are frequently \"spiking\" very high, notably when performing \"gettxoutsetinfo\")\r\n\r\nAlso I don't understand why Bitcoind core is flushing EVERYTHING including its whole cache of block data (about 760GB) according to logs to return to just a single block (about 45MB). shouldn't we split the cache in two parts, so that we flush it just in half, and then maintain two metafiles (one for the older view of the chainstate, another for the most recent, making sure that the older view will remain intact and will not be deleted as long as the new state is not finished: if the new state fails, at least we can recover from the previous state. old indexes don't need to be deleted immediately if they can be still referenced from the old state: this allow safe recovery in all cases (even if the daemon crashes for any reason and is unable to flush its state completely).",
      "created_at" : "2022-08-11T14:53:47Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212101325",
      "id" : 1212101325,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IPzLN",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212101325/reactions"
      },
      "updated_at" : "2022-08-11T15:05:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212101325",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Let's focus on reproducing. I am not convinced LevelDB (or even anything related to the chainstate at all) is at fault here, because the fact that `reconsiderblock` caused things to get unstruck implies there wasn't any actual on-disk corruption.\r\n\r\n> Also I don't understand why Bitcoind core is flushing EVERYTHING including its whole cache of block data (about 760GB) \r\n\r\nOnly the chainstate database is cached by Bitcoin Core, which is a few GB typically (and only up to the dbcache setting of that is kept in memory).\r\n\r\n> according to logs to return to just a single block (about 45MB).\r\n\r\nBlocks are never more than 4 MB, and aren't stored in LevelDB (or any kind of database). They're stored in raw blk*.dat files.",
      "created_at" : "2022-08-11T15:19:47Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212136090",
      "id" : 1212136090,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IP7qa",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212136090/reactions"
      },
      "updated_at" : "2022-08-11T15:23:04Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212136090",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "I'd guess the most likely cause would be a cosmic ray or old/overheated CPU/RAM, as the issue wasn't persistent.",
      "created_at" : "2022-08-11T15:31:07Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212149709",
      "id" : 1212149709,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IP-_N",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212149709/reactions"
      },
      "updated_at" : "2022-08-11T15:31:07Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212149709",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "No Marco, cosmic rays are very unlikely, and overheating is definitely not the case. The bug is persistent even if it occurs \"unpredictably\" (for now because we don't know the exact cause) and in lot of different hardware and OS configurations, and even when running on very reliable systems (like Azure and Amazon VMs). And I have not noted any hardware issue reported by the OS or any problem in the filesystem which is always \"clean\", and based on very reliable RAID stores with multiple layers of hardware and software checks. It looks very much like a race issue in Bitcoin Core implementation itself (or its dependancies like LevelDB), which is more likely to occur on very fast machines and with very fast Internet connections.\r\nAll I did to limit the rate of these errors was to voluntarily slowdown Bitcoin Core. And I've never detected any block corruption when I compare the regular snapshots of data I make with backups or across the different hosts that I've tried. They just fail at different time, but they all fail sometime.",
      "created_at" : "2022-08-11T16:29:25Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212215679",
      "id" : 1212215679,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IQPF_",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212215679/reactions"
      },
      "updated_at" : "2022-08-11T16:33:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212215679",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Do you have exact steps to reproduce on Azure or Amazon? Please make sure to include exact and complete steps, including all settings that are changed on the OS layer or elsewhere.",
      "created_at" : "2022-08-11T16:42:52Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212228301",
      "id" : 1212228301,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IQSLN",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212228301/reactions"
      },
      "updated_at" : "2022-08-11T16:42:52Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212228301",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "The steps are just configure a standard VM with default settings. I chose the most common OSes with little configuration. I chose the standard binary releases. jkuste like anyone would do at home on their PC.\r\nI tried many different configs (since many months), none have successed. We see failures happening after about 2 hours, or sometimes just after less than 10 minutes. I can erase all the daa and restart, this just fails at different moments, but it never completes.\r\nIn fact I have no idea about why it works for many other people. But they don't tell us why. Most probably many other have tried and already abandoned rapidly since long.",
      "created_at" : "2022-08-11T17:06:25Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212258006",
      "id" : 1212258006,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IQZbW",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212258006/reactions"
      },
      "updated_at" : "2022-08-11T17:07:22Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212258006",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Are you absolutely sure you are using \"default\" settings? You said the same thing in the last issue, and I wasn't able to reproduce with default settings: https://github.com/bitcoin/bitcoin/issues/25726#issuecomment-1203088286",
      "created_at" : "2022-08-11T17:24:40Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212273740",
      "id" : 1212273740,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IQdRM",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212273740/reactions"
      },
      "updated_at" : "2022-08-11T17:24:40Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212273740",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I just run \"bitcoind\" with no options its logs in debug.log and on the console, unless I give the option to not no log anything on th console or in \"debug.log\" (this makes it run faster), or I use\r\n\r\n> $ bitcoin-cli debug '[]' '[\"all\"]'\r\n\r\nto disable new log outputs (it just logs the startup or shutdown and \" UpdateTip: new best=*\" messages, still at a very high rate.)",
      "created_at" : "2022-08-11T20:19:47Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212455409",
      "id" : 1212455409,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585IRJnx",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212455409/reactions"
      },
      "updated_at" : "2022-08-11T20:24:46Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212455409",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "> > But may be there are other competing softwares that could work such as https://www.bitcoinabc.org/ (if they've detected such attack and are able to isolate and fix it)?\r\n> \r\n> That software is for a different currency, with different consensus rules. It will not synchronize with the Bitcoin network/chain/currency.\r\n\r\nWhy do I see them connected to the Bitcoin chain (according to their user agent string)? What are they doing there? They are just \"listening\" and not emitting any transaction? But frequently blocks are downloaded *from* them.",
      "created_at" : "2022-08-12T05:13:31Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1212736619",
      "id" : 1212736619,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585ISORr",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212736619/reactions"
      },
      "updated_at" : "2022-08-12T05:13:31Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1212736619",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I've made other tests by reducing a lot the dbcache size to just 4MB (and the mempool size to its minimum allowed of 5MB, even if it's empty during the IBD phase, because that unused mempool is used to augment the dbcache size.\r\n\r\nWhat I observe as that when the dbcache is full, and compacts the index files, it may happen that it DELETE an index file (in the chainstate) too early (this index was generated in an eraly pass, and survived several passes where the dbcache was full. But at one point, it remains jsut as one of the \"oldest\" one and it is unconditionally deleted even if it is referenced in newer indexes that were added in later passes.\r\n\r\nSo this is not a data corruption, but a logical error when deleting indexes.\r\n\r\nTo make this clear, I purged the logs from \"New tips\" and here is when a specific index file #9575 for the \"chainstate\" was created, then survived serval \"passes\" of compression of the \"cache\", and finally deleted just before it was accessed again (and that access failed, it was deleted by error).\r\n\r\n```\r\n2022-08-12T08:39:06Z UpdateTip: new best=00000000000000656391cde7c780eb05cfff19176bae8cd7810a9db66d6df2c1 height=215930 version=0x00000001 log2_work=69.270036 tx=10937927 date='2013-01-10T03:00:11Z' progress=0.014484 cache=5.6MiB(40342txo)\r\n\r\n\r\n\r\n2022-08-12T08:39:06Z leveldb: Generated table #9775@2: 40143 keys, 2173277 bytes\r\n2022-08-12T08:39:07Z Cache size (6923712) exceeds total space (6835008)\r\n2022-08-12T08:39:07Z leveldb: compacted to: files[ 1 6 58 45 0 0 0 ]\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #8916\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9485\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9486\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9487\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9488\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9489\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9490\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9493\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9656\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9728\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9729\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9730\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9731\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9733\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9734\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9735\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9736\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9737\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9738\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9739\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9749\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9750\r\n2022-08-12T08:39:07Z leveldb: Delete type=2 #9764\r\n2022-08-12T08:39:07Z WriteBatch memory usage: db=index, before=0.0MiB, after=0.0MiB\r\n2022-08-12T08:39:07Z leveldb: Level-0 table #9783: started\r\n2022-08-12T08:39:07Z WriteBatch memory usage: db=chainstate, before=3.8MiB, after=7.6MiB\r\n2022-08-12T08:39:07Z leveldb: Level-0 table #9783: 2532965 bytes OK\r\n2022-08-12T08:39:07Z leveldb: Delete type=0 #9759\r\n2022-08-12T08:39:07Z leveldb: Compacting 2@0 + 6@1 files\r\n2022-08-12T08:39:07Z leveldb: Generated table #9784@0: 43672 keys, 2180595 bytes\r\n2022-08-12T08:39:07Z leveldb: Generated table #9785@0: 8527 keys, 410180 bytes\r\n2022-08-12T08:39:07Z leveldb: Generated table #9786@0: 47576 keys, 2185414 bytes\r\n2022-08-12T08:39:07Z leveldb: Generated table #9787@0: 4499 keys, 204380 bytes\r\n2022-08-12T08:39:07Z leveldb: Generated table #9788@0: 47828 keys, 2185234 bytes\r\n2022-08-12T08:39:07Z leveldb: Generated table #9789@0: 10969 keys, 496878 bytes\r\n2022-08-12T08:39:08Z leveldb: Generated table #9790@0: 47342 keys, 2184113 bytes\r\n2022-08-12T08:39:08Z leveldb: Generated table #9791@0: 4074 keys, 182887 bytes\r\n2022-08-12T08:39:08Z leveldb: Generated table #9792@0: 48512 keys, 2184988 bytes\r\n2022-08-12T08:39:08Z leveldb: Generated table #9793@0: 4761 keys, 216771 bytes\r\n2022-08-12T08:39:08Z leveldb: Compacted 2@0 + 6@1 files => 12431440 bytes\r\n2022-08-12T08:39:08Z leveldb: compacted to: files[ 0 10 58 45 0 0 0 ]\r\n2022-08-12T08:39:08Z leveldb: Compacting 1@1 + 6@2 files\r\n2022-08-12T08:39:08Z leveldb: Generated table #9794@1: 45350 keys, 2181751 bytes\r\n2022-08-12T08:39:08Z leveldb: Generated table #9795@1: 38913 keys, 2171326 bytes\r\n2022-08-12T08:39:08Z leveldb: Generated table #9796@1: 35041 keys, 1913554 bytes\r\n2022-08-12T08:39:08Z leveldb: Compacted 1@1 + 6@2 files => 6266631 bytes\r\n2022-08-12T08:39:08Z leveldb: compacted to: files[ 0 9 55 45 0 0 0 ]\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9624\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9625\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9657\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9751\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9752\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9753\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9754\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9755\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9756\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9760\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9770\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9771\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9772\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9783\r\n2022-08-12T08:39:08Z leveldb: Delete type=2 #9785\r\n2022-08-12T08:39:08Z leveldb: Expanding@1 1+11 (2185414+21943875 bytes) to 2+11 (2389794+21943875 bytes)\r\n2022-08-12T08:39:08Z leveldb: Compacting 2@1 + 11@2 files\r\n2022-08-12T08:39:08Z leveldb: Generated table #9797@1: 40063 keys, 2172908 bytes\r\n2022-08-12T08:39:08Z leveldb: Generated table #9798@1: 40028 keys, 2176547 bytes\r\n2022-08-12T08:39:08Z leveldb: Generated table #9799@1: 38815 keys, 2170398 bytes\r\n2022-08-12T08:39:08Z leveldb: Generated table #9800@1: 39765 keys, 2172175 bytes\r\n2022-08-12T08:39:09Z leveldb: Generated table #9801@1: 39211 keys, 2171465 bytes\r\n2022-08-12T08:39:09Z leveldb: Generated table #9802@1: 39092 keys, 2174567 bytes\r\n2022-08-12T08:39:09Z leveldb: Generated table #9803@1: 40303 keys, 2173785 bytes\r\n2022-08-12T08:39:09Z leveldb: Generated table #9804@1: 39612 keys, 2172109 bytes\r\n2022-08-12T08:39:09Z leveldb: Generated table #9805@1: 39188 keys, 2171479 bytes\r\n2022-08-12T08:39:09Z leveldb: Generated table #9806@1: 39821 keys, 2176196 bytes\r\n2022-08-12T08:39:09Z leveldb: Generated table #9807@1: 16248 keys, 858058 bytes\r\n2022-08-12T08:39:09Z leveldb: Compacted 2@1 + 11@2 files => 22589687 bytes\r\n2022-08-12T08:39:09Z leveldb: compacted to: files[ 0 7 55 45 0 0 0 ]\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9319\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9626\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9627\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9628\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9629\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9632\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9633\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9634\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9635\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9636\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9637\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9786\r\n2022-08-12T08:39:09Z leveldb: Delete type=2 #9787\r\n2022-08-12T08:39:09Z leveldb: Expanding@1 1+10 (2184113+21728027 bytes) to 2+10 (2367000+21728027 bytes)\r\n2022-08-12T08:39:09Z leveldb: Compacting 2@1 + 10@2 files\r\n2022-08-12T08:39:09Z leveldb: Generated table #9808@1: 39168 keys, 2170981 bytes\r\n2022-08-12T08:39:09Z leveldb: Generated table #9809@1: 39842 keys, 2172945 bytes\r\n\r\n\r\n\r\n2022-08-12T08:39:09Z Cache size (6992256) exceeds total space (6835008)\r\n2022-08-12T08:39:09Z leveldb: Generated table #9810@1: 39592 keys, 2172424 bytes\r\n2022-08-12T08:39:10Z WriteBatch memory usage: db=index, before=0.0MiB, after=0.0MiB\r\n2022-08-12T08:39:10Z leveldb: Generated table #9811@1: 39167 keys, 2171711 bytes\r\n2022-08-12T08:39:10Z leveldb: Level-0 table #9813: started\r\n2022-08-12T08:39:10Z WriteBatch memory usage: db=chainstate, before=3.8MiB, after=7.6MiB\r\n2022-08-12T08:39:10Z leveldb: Level-0 table #9813: 2537527 bytes OK\r\n2022-08-12T08:39:10Z leveldb: Delete type=0 #9782\r\n2022-08-12T08:39:10Z leveldb: Generated table #9814@1: 39556 keys, 2175754 bytes\r\n2022-08-12T08:39:10Z leveldb: Generated table #9815@1: 39455 keys, 2175033 bytes\r\n2022-08-12T08:39:10Z leveldb: Generated table #9816@1: 40154 keys, 2176692 bytes\r\n2022-08-12T08:39:10Z leveldb: Generated table #9817@1: 39655 keys, 2172245 bytes\r\n2022-08-12T08:39:10Z leveldb: Generated table #9818@1: 38929 keys, 2174589 bytes\r\n2022-08-12T08:39:10Z leveldb: Generated table #9819@1: 41090 keys, 2174505 bytes\r\n2022-08-12T08:39:10Z leveldb: Generated table #9820@1: 11097 keys, 630285 bytes\r\n2022-08-12T08:39:10Z leveldb: Compacted 2@1 + 10@2 files => 22367164 bytes\r\n2022-08-12T08:39:10Z leveldb: compacted to: files[ 1 5 56 45 0 0 0 ]\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9594\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9595\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9596\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9597\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9598\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9599\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9602\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9603\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9604\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9605\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9790\r\n2022-08-12T08:39:10Z leveldb: Delete type=2 #9791\r\n2022-08-12T08:39:10Z leveldb: Compacting 1@0 + 5@1 files\r\n2022-08-12T08:39:11Z leveldb: Generated table #9821@0: 44382 keys, 2180697 bytes\r\n2022-08-12T08:39:11Z leveldb: Generated table #9822@0: 21785 keys, 1072502 bytes\r\n2022-08-12T08:39:11Z leveldb: Generated table #9823@0: 5473 keys, 286217 bytes\r\n2022-08-12T08:39:11Z leveldb: Generated table #9824@0: 47921 keys, 2185021 bytes\r\n2022-08-12T08:39:11Z leveldb: Generated table #9825@0: 9491 keys, 433795 bytes\r\n2022-08-12T08:39:11Z leveldb: Generated table #9826@0: 11317 keys, 550703 bytes\r\n2022-08-12T08:39:11Z leveldb: Generated table #9827@0: 48629 keys, 2186670 bytes\r\n2022-08-12T08:39:11Z leveldb: Generated table #9828@0: 8308 keys, 377653 bytes\r\n2022-08-12T08:39:11Z leveldb: Compacted 1@0 + 5@1 files => 9273258 bytes\r\n2022-08-12T08:39:11Z leveldb: compacted to: files[ 0 8 56 45 0 0 0 ]\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9784\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9788\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9789\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9792\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9793\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9813\r\n2022-08-12T08:39:11Z leveldb: Compacting 1@1 + 5@2 files\r\n2022-08-12T08:39:11Z leveldb: Generated table #9829@1: 48934 keys, 2185074 bytes\r\n2022-08-12T08:39:11Z leveldb: Generated table #9830@1: 38447 keys, 1718958 bytes\r\n2022-08-12T08:39:11Z leveldb: Generated table #9831@1: 49035 keys, 2185196 bytes\r\n2022-08-12T08:39:11Z leveldb: Generated table #9832@1: 41810 keys, 2174146 bytes\r\n2022-08-12T08:39:11Z leveldb: Generated table #9833@1: 24075 keys, 1340799 bytes\r\n2022-08-12T08:39:11Z leveldb: Compacted 1@1 + 5@2 files => 9604173 bytes\r\n2022-08-12T08:39:11Z leveldb: compacted to: files[ 0 7 56 45 0 0 0 ]\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9767\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9768\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9769\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9794\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9795\r\n2022-08-12T08:39:11Z leveldb: Delete type=2 #9822\r\n2022-08-12T08:39:11Z leveldb: Compacting 1@2 + 4@3 files\r\n2022-08-12T08:39:12Z leveldb: Generated table #9834@2: 40301 keys, 2174121 bytes\r\n2022-08-12T08:39:12Z leveldb: Generated table #9835@2: 39719 keys, 2172310 bytes\r\n2022-08-12T08:39:12Z leveldb: Generated table #9836@2: 38897 keys, 2170931 bytes\r\n\r\n\r\n\r\n2022-08-12T08:39:12Z Cache size (6878304) exceeds total space (6835008)\r\n2022-08-12T08:39:12Z leveldb: Generated table #9837@2: 23903 keys, 1294937 bytes\r\n2022-08-12T08:39:12Z leveldb: Compacted 1@2 + 4@3 files => 7812299 bytes\r\n2022-08-12T08:39:12Z leveldb: compacted to: files[ 0 7 55 45 0 0 0 ]\r\n2022-08-12T08:39:12Z leveldb: Delete type=2 #9494\r\n2022-08-12T08:39:12Z leveldb: Delete type=2 #9495\r\n2022-08-12T08:39:12Z leveldb: Delete type=2 #9765\r\n2022-08-12T08:39:12Z leveldb: Delete type=2 #9780\r\n2022-08-12T08:39:12Z leveldb: Delete type=2 #9781\r\n2022-08-12T08:39:12Z leveldb: Level-0 table #9839: started\r\n2022-08-12T08:39:12Z WriteBatch memory usage: db=chainstate, before=3.8MiB, after=7.6MiB\r\n2022-08-12T08:39:12Z leveldb: Level-0 table #9839: 2498978 bytes OK\r\n2022-08-12T08:39:12Z leveldb: Delete type=0 #9812\r\n2022-08-12T08:39:12Z leveldb: Compacting 1@0 + 7@1 files\r\n2022-08-12T08:39:12Z leveldb: Generated table #9840@0: 45613 keys, 2183633 bytes\r\n2022-08-12T08:39:12Z leveldb: Generated table #9841@0: 23249 keys, 1135569 bytes\r\n2022-08-12T08:39:12Z leveldb: Generated table #9842@0: 10138 keys, 503820 bytes\r\n2022-08-12T08:39:12Z leveldb: Generated table #9843@0: 48488 keys, 2186035 bytes\r\n2022-08-12T08:39:12Z leveldb: Generated table #9844@0: 18620 keys, 843849 bytes\r\n2022-08-12T08:39:12Z leveldb: Generated table #9845@0: 10398 keys, 520406 bytes\r\n2022-08-12T08:39:12Z leveldb: Generated table #9846@0: 48985 keys, 2186338 bytes\r\n2022-08-12T08:39:12Z leveldb: Generated table #9847@0: 10405 keys, 468151 bytes\r\n2022-08-12T08:39:12Z leveldb: Compacted 1@0 + 7@1 files => 10027801 bytes\r\n2022-08-12T08:39:13Z leveldb: compacted to: files[ 0 8 55 45 0 0 0 ]\r\n2022-08-12T08:39:13Z leveldb: Compacting 1@1 + 7@2 files\r\n2022-08-12T08:39:13Z leveldb: Generated table #9848@1: 50790 keys, 2187264 bytes\r\n2022-08-12T08:39:13Z leveldb: Generated table #9849@1: 50090 keys, 2185479 bytes\r\n2022-08-12T08:39:13Z leveldb: Generated table #9850@1: 17474 keys, 790414 bytes\r\n2022-08-12T08:39:13Z leveldb: Generated table #9851@1: 49508 keys, 2187084 bytes\r\n2022-08-12T08:39:13Z leveldb: Generated table #9852@1: 46851 keys, 2076869 bytes\r\n2022-08-12T08:39:13Z leveldb: Generated table #9853@1: 38937 keys, 2171072 bytes\r\n2022-08-12T08:39:13Z leveldb: Generated table #9854@1: 39432 keys, 2172351 bytes\r\n2022-08-12T08:39:13Z leveldb: Generated table #9855@1: 8414 keys, 453601 bytes\r\n2022-08-12T08:39:13Z leveldb: Compacted 1@1 + 7@2 files => 14224134 bytes\r\n2022-08-12T08:39:13Z leveldb: compacted to: files[ 0 7 56 45 0 0 0 ]\r\n2022-08-12T08:39:13Z leveldb: Delete type=2 #9821\r\n2022-08-12T08:39:13Z leveldb: Delete type=2 #9823\r\n2022-08-12T08:39:13Z leveldb: Delete type=2 #9824\r\n2022-08-12T08:39:13Z leveldb: Delete type=2 #9825\r\n2022-08-12T08:39:13Z leveldb: Delete type=2 #9826\r\n2022-08-12T08:39:13Z leveldb: Delete type=2 #9827\r\n2022-08-12T08:39:13Z leveldb: Delete type=2 #9828\r\n2022-08-12T08:39:13Z leveldb: Delete type=2 #9839\r\n2022-08-12T08:39:13Z leveldb: Compacting 1@1 + 6@2 files\r\n2022-08-12T08:39:13Z leveldb: Generated table #9856@1: 54034 keys, 2192179 bytes\r\n2022-08-12T08:39:13Z leveldb: Generated table #9857@1: 54644 keys, 2192950 bytes\r\n2022-08-12T08:39:14Z leveldb: Generated table #9858@1: 53467 keys, 2191225 bytes\r\n2022-08-12T08:39:14Z leveldb: Generated table #9859@1: 53435 keys, 2190814 bytes\r\n2022-08-12T08:39:14Z leveldb: Generated table #9860@1: 22479 keys, 1014350 bytes\r\n2022-08-12T08:39:14Z leveldb: Generated table #9861@1: 19814 keys, 949923 bytes\r\n\r\n\r\n\r\n2022-08-12T08:39:14Z Cache size (6853472) exceeds total space (6835008)\r\n2022-08-12T08:39:14Z leveldb: Generated table #9862@1: 50721 keys, 2188402 bytes\r\n2022-08-12T08:39:14Z leveldb: Generated table #9863@1: 2000 keys, 85505 bytes\r\n2022-08-12T08:39:14Z leveldb: Compacted 1@1 + 6@2 files => 13005348 bytes\r\n2022-08-12T08:39:14Z WriteBatch memory usage: db=index, before=0.0MiB, after=0.0MiB\r\n2022-08-12T08:39:14Z leveldb: compacted to: files[ 0 6 58 45 0 0 0 ]\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9757\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9758\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9761\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9762\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9763\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9766\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9796\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9829\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9830\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9831\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9832\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9833\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9840\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9841\r\n2022-08-12T08:39:14Z leveldb: Delete type=2 #9848\r\n2022-08-12T08:39:14Z leveldb: Compacting 1@2 + 7@3 files\r\n2022-08-12T08:39:14Z leveldb: Level-0 table #9866: started\r\n2022-08-12T08:39:14Z WriteBatch memory usage: db=chainstate, before=3.8MiB, after=7.6MiB\r\n2022-08-12T08:39:14Z leveldb: Level-0 table #9866: 2590435 bytes OK\r\n2022-08-12T08:39:14Z leveldb: Delete type=0 #9838\r\n2022-08-12T08:39:14Z leveldb: Generated table #9864@2: 39569 keys, 2173066 bytes\r\n2022-08-12T08:39:14Z leveldb: Generated table #9867@2: 39540 keys, 2172144 bytes\r\n2022-08-12T08:39:14Z leveldb: Generated table #9868@2: 38826 keys, 2170693 bytes\r\n2022-08-12T08:39:14Z leveldb: Generated table #9869@2: 39086 keys, 2171889 bytes\r\n2022-08-12T08:39:15Z leveldb: Generated table #9870@2: 38165 keys, 2113933 bytes\r\n2022-08-12T08:39:15Z leveldb: Compacted 1@2 + 7@3 files => 10801725 bytes\r\n2022-08-12T08:39:15Z leveldb: compacted to: files[ 1 6 57 43 0 0 0 ]\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #8316\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #8918\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #8919\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9340\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9496\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9497\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9837\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9862\r\n2022-08-12T08:39:15Z leveldb: Compacting 1@0 + 6@1 files\r\n2022-08-12T08:39:15Z leveldb: Generated table #9871@0: 25762 keys, 1384300 bytes\r\n2022-08-12T08:39:15Z leveldb: Generated table #9872@0: 14959 keys, 738733 bytes\r\n2022-08-12T08:39:15Z leveldb: Generated table #9873@0: 48494 keys, 2185670 bytes\r\n2022-08-12T08:39:15Z leveldb: Generated table #9874@0: 23028 keys, 1042516 bytes\r\n2022-08-12T08:39:15Z leveldb: Generated table #9875@0: 15480 keys, 765505 bytes\r\n2022-08-12T08:39:15Z leveldb: Generated table #9876@0: 48988 keys, 2185593 bytes\r\n2022-08-12T08:39:15Z leveldb: Generated table #9877@0: 13248 keys, 593809 bytes\r\n2022-08-12T08:39:15Z leveldb: Compacted 1@0 + 6@1 files => 8896126 bytes\r\n2022-08-12T08:39:15Z leveldb: compacted to: files[ 0 7 57 43 0 0 0 ]\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9842\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9843\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9844\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9845\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9846\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9847\r\n2022-08-12T08:39:15Z leveldb: Delete type=2 #9866\r\n2022-08-12T08:39:15Z leveldb: Compacting 1@1 + 13@2 files\r\n2022-08-12T08:39:15Z leveldb: Generated table #9878@1: 54038 keys, 2191174 bytes\r\n2022-08-12T08:39:15Z leveldb: Generated table #9879@1: 54588 keys, 2192716 bytes\r\n2022-08-12T08:39:15Z leveldb: Generated table #9880@1: 53487 keys, 2190523 bytes\r\n2022-08-12T08:39:15Z leveldb: Generated table #9881@1: 53431 keys, 2192014 bytes\r\n2022-08-12T08:39:16Z leveldb: Generated table #9882@1: 27094 keys, 1220859 bytes\r\n2022-08-12T08:39:16Z leveldb: Generated table #9883@1: 23871 keys, 1141856 bytes\r\n2022-08-12T08:39:16Z leveldb: Generated table #9884@1: 49802 keys, 2186049 bytes\r\n2022-08-12T08:39:16Z leveldb: Generated table #9885@1: 17422 keys, 786360 bytes\r\n2022-08-12T08:39:16Z leveldb: Generated table #9886@1: 49305 keys, 2186101 bytes\r\n2022-08-12T08:39:16Z leveldb: Generated table #9887@1: 49063 keys, 2174883 bytes\r\n2022-08-12T08:39:16Z leveldb: Generated table #9888@1: 41031 keys, 2173940 bytes\r\n\r\n\r\n\r\n2022-08-12T08:39:16Z Cache size (6894528) exceeds total space (6835008)\r\n2022-08-12T08:39:16Z leveldb: Generated table #9889@1: 38978 keys, 2171396 bytes\r\n2022-08-12T08:39:16Z leveldb: Generated table #9890@1: 7933 keys, 427011 bytes\r\n2022-08-12T08:39:16Z leveldb: Compacted 1@1 + 13@2 files => 23234882 bytes\r\n2022-08-12T08:39:16Z leveldb: compacted to: files[ 0 6 57 43 0 0 0 ]\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9849\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9850\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9851\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9852\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9853\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9854\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9856\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9857\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9858\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9859\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9860\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9861\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9863\r\n2022-08-12T08:39:16Z leveldb: Delete type=2 #9871\r\n2022-08-12T08:39:16Z leveldb: Compacting 1@2 + 8@3 files\r\n2022-08-12T08:39:16Z WriteBatch memory usage: db=index, before=0.0MiB, after=0.0MiB\r\n2022-08-12T08:39:17Z WriteBatch memory usage: db=chainstate, before=3.7MiB, after=7.6MiB\r\n2022-08-12T08:39:17Z leveldb: Generated table #9891@2: 39575 keys, 2171913 bytes\r\n2022-08-12T08:39:17Z leveldb: Level-0 table #9893: started\r\n2022-08-12T08:39:17Z leveldb: Level-0 table #9893: 2511900 bytes OK\r\n2022-08-12T08:39:17Z leveldb: Delete type=0 #9865\r\n2022-08-12T08:39:17Z leveldb: Generated table #9894@2: 39629 keys, 2175263 bytes\r\n2022-08-12T08:39:17Z leveldb: Generated table #9895@2: 38788 keys, 2171237 bytes\r\n2022-08-12T08:39:17Z leveldb: Generated table #9896@2: 38909 keys, 2171009 bytes\r\n2022-08-12T08:39:17Z leveldb: Generated table #9897@2: 39438 keys, 2172667 bytes\r\n2022-08-12T08:39:17Z leveldb: Generated table #9898@2: 39300 keys, 2171502 bytes\r\n2022-08-12T08:39:17Z leveldb: Generated table #9899@2: 38981 keys, 2174643 bytes\r\n2022-08-12T08:39:17Z leveldb: Generated table #9900@2: 39547 keys, 2171856 bytes\r\n2022-08-12T08:39:17Z leveldb: Generated table #9901@2: 10019 keys, 529942 bytes\r\n2022-08-12T08:39:17Z leveldb: Compacted 1@2 + 8@3 files => 17910032 bytes\r\n2022-08-12T08:39:17Z leveldb: compacted to: files[ 1 6 56 44 0 0 0 ]\r\n2022-08-12T08:39:17Z leveldb: Delete type=2 #8920\r\n2022-08-12T08:39:17Z leveldb: Delete type=2 #9447\r\n2022-08-12T08:39:17Z leveldb: Delete type=2 #9448\r\n2022-08-12T08:39:17Z leveldb: Delete type=2 #9864\r\n2022-08-12T08:39:17Z leveldb: Delete type=2 #9867\r\n2022-08-12T08:39:17Z leveldb: Delete type=2 #9868\r\n2022-08-12T08:39:17Z leveldb: Delete type=2 #9869\r\n2022-08-12T08:39:17Z leveldb: Delete type=2 #9870\r\n2022-08-12T08:39:17Z leveldb: Delete type=2 #9884\r\n2022-08-12T08:39:17Z leveldb: Compacting 1@0 + 6@1 files\r\n2022-08-12T08:39:18Z leveldb: Generated table #9902@0: 26973 keys, 1405415 bytes\r\n2022-08-12T08:39:18Z leveldb: Generated table #9903@0: 19237 keys, 931085 bytes\r\n2022-08-12T08:39:18Z leveldb: Generated table #9904@0: 48680 keys, 2185147 bytes\r\n2022-08-12T08:39:18Z leveldb: Generated table #9905@0: 26483 keys, 1194088 bytes\r\n2022-08-12T08:39:18Z leveldb: Generated table #9906@0: 19704 keys, 956353 bytes\r\n2022-08-12T08:39:18Z leveldb: Generated table #9907@0: 49169 keys, 2186145 bytes\r\n2022-08-12T08:39:18Z leveldb: Generated table #9908@0: 15898 keys, 708432 bytes\r\n2022-08-12T08:39:18Z leveldb: Compacted 1@0 + 6@1 files => 9566665 bytes\r\n2022-08-12T08:39:18Z leveldb: compacted to: files[ 0 7 56 44 0 0 0 ]\r\n2022-08-12T08:39:18Z leveldb: Delete type=2 #9872\r\n2022-08-12T08:39:18Z leveldb: Delete type=2 #9873\r\n2022-08-12T08:39:18Z leveldb: Delete type=2 #9874\r\n2022-08-12T08:39:18Z leveldb: Delete type=2 #9875\r\n2022-08-12T08:39:18Z leveldb: Delete type=2 #9876\r\n2022-08-12T08:39:18Z leveldb: Delete type=2 #9877\r\n2022-08-12T08:39:18Z leveldb: Delete type=2 #9893\r\n2022-08-12T08:39:18Z leveldb: Compacting 1@1 + 12@2 files\r\n2022-08-12T08:39:18Z leveldb: Generated table #9909@1: 54017 keys, 2191218 bytes\r\n2022-08-12T08:39:18Z leveldb: Generated table #9910@1: 54609 keys, 2193333 bytes\r\n2022-08-12T08:39:18Z leveldb: Generated table #9911@1: 53537 keys, 2190172 bytes\r\n2022-08-12T08:39:18Z leveldb: Generated table #9912@1: 53426 keys, 2190468 bytes\r\n2022-08-12T08:39:18Z leveldb: Generated table #9913@1: 31248 keys, 1399514 bytes\r\n2022-08-12T08:39:19Z leveldb: Generated table #9914@1: 28096 keys, 1332480 bytes\r\n2022-08-12T08:39:19Z leveldb: Generated table #9915@1: 23510 keys, 1091463 bytes\r\n2022-08-12T08:39:19Z leveldb: Generated table #9916@1: 49394 keys, 2186227 bytes\r\n\r\n\r\n\r\n2022-08-12T08:39:19Z Cache size (6921120) exceeds total space (6835008)\r\n2022-08-12T08:39:19Z leveldb: Generated table #9917@1: 49584 keys, 2187024 bytes\r\n2022-08-12T08:39:19Z WriteBatch memory usage: db=index, before=0.0MiB, after=0.0MiB\r\n2022-08-12T08:39:19Z leveldb: Generated table #9918@1: 4091 keys, 182997 bytes\r\n2022-08-12T08:39:19Z leveldb: Level-0 table #9921: started\r\n2022-08-12T08:39:19Z WriteBatch memory usage: db=chainstate, before=3.9MiB, after=7.7MiB\r\n2022-08-12T08:39:19Z leveldb: Level-0 table #9921: 2579487 bytes OK\r\n2022-08-12T08:39:19Z leveldb: Delete type=0 #9892\r\n2022-08-12T08:39:19Z leveldb: Generated table #9919@1: 41110 keys, 2173479 bytes\r\n2022-08-12T08:39:19Z leveldb: Generated table #9922@1: 39016 keys, 2171370 bytes\r\n2022-08-12T08:39:19Z leveldb: Generated table #9923@1: 8263 keys, 446542 bytes\r\n2022-08-12T08:39:19Z leveldb: Compacted 1@1 + 12@2 files => 21936287 bytes\r\n2022-08-12T08:39:19Z leveldb: compacted to: files[ 1 6 57 44 0 0 0 ]\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9878\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9879\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9880\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9881\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9882\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9883\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9885\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9886\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9887\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9888\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9889\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9890\r\n2022-08-12T08:39:19Z leveldb: Delete type=2 #9902\r\n2022-08-12T08:39:19Z leveldb: Compacting 1@0 + 6@1 files\r\n2022-08-12T08:39:19Z leveldb: Generated table #9924@0: 26159 keys, 1392720 bytes\r\n2022-08-12T08:39:19Z leveldb: Generated table #9925@0: 24492 keys, 1176015 bytes\r\n2022-08-12T08:39:19Z leveldb: Generated table #9926@0: 48757 keys, 2186768 bytes\r\n2022-08-12T08:39:20Z leveldb: Generated table #9927@0: 30455 keys, 1373435 bytes\r\n2022-08-12T08:39:20Z leveldb: Generated table #9928@0: 24014 keys, 1158916 bytes\r\n2022-08-12T08:39:20Z leveldb: Generated table #9929@0: 49220 keys, 2186669 bytes\r\n2022-08-12T08:39:20Z leveldb: Generated table #9930@0: 18409 keys, 820476 bytes\r\n2022-08-12T08:39:20Z leveldb: Compacted 1@0 + 6@1 files => 10294999 bytes\r\n2022-08-12T08:39:20Z leveldb: compacted to: files[ 0 7 57 44 0 0 0 ]\r\n2022-08-12T08:39:20Z leveldb: Compacting 1@1 + 12@2 files\r\n2022-08-12T08:39:20Z leveldb: Generated table #9931@1: 54070 keys, 2191403 bytes\r\n2022-08-12T08:39:20Z leveldb: Generated table #9932@1: 54644 keys, 2193010 bytes\r\n2022-08-12T08:39:20Z leveldb: Generated table #9933@1: 53462 keys, 2190832 bytes\r\n2022-08-12T08:39:20Z leveldb: Generated table #9934@1: 53423 keys, 2192131 bytes\r\n2022-08-12T08:39:20Z leveldb: Generated table #9935@1: 35731 keys, 1603095 bytes\r\n2022-08-12T08:39:20Z leveldb: Generated table #9936@1: 32496 keys, 1531874 bytes\r\n2022-08-12T08:39:20Z leveldb: Generated table #9937@1: 28163 keys, 1317182 bytes\r\n2022-08-12T08:39:21Z leveldb: Generated table #9938@1: 49394 keys, 2186144 bytes\r\n2022-08-12T08:39:21Z leveldb: Generated table #9939@1: 49563 keys, 2185964 bytes\r\n2022-08-12T08:39:21Z leveldb: Generated table #9940@1: 8317 keys, 367743 bytes\r\n2022-08-12T08:39:21Z leveldb: Generated table #9941@1: 41190 keys, 2173751 bytes\r\n2022-08-12T08:39:21Z leveldb: Generated table #9942@1: 38956 keys, 2171454 bytes\r\n2022-08-12T08:39:21Z leveldb: Generated table #9943@1: 542 keys, 29551 bytes\r\n2022-08-12T08:39:21Z leveldb: Compacted 1@1 + 12@2 files => 22334134 bytes\r\n2022-08-12T08:39:21Z leveldb: compacted to: files[ 0 6 58 44 0 0 0 ]\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9903\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9904\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9905\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9906\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9907\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9908\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9909\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9910\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9911\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9912\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9913\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9914\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9915\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9916\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9917\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9918\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9919\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9921\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9922\r\n2022-08-12T08:39:21Z leveldb: Delete type=2 #9924\r\n2022-08-12T08:39:21Z leveldb: Compacting 1@1 + 10@2 files\r\n\r\n\r\n\r\n2022-08-12T08:39:21Z Cache size (6838048) exceeds total space (6835008)\r\n2022-08-12T08:39:21Z leveldb: Generated table #9944@1: 38942 keys, 2172325 bytes\r\n2022-08-12T08:39:21Z WriteBatch memory usage: db=index, before=0.0MiB, after=0.0MiB\r\n2022-08-12T08:39:21Z leveldb: Generated table #9945@1: 38732 keys, 2170551 bytes\r\n2022-08-12T08:39:21Z leveldb: Level-0 table #9947: started\r\n2022-08-12T08:39:21Z WriteBatch memory usage: db=chainstate, before=3.8MiB, after=7.5MiB\r\n2022-08-12T08:39:21Z leveldb: Level-0 table #9947: 2591053 bytes OK\r\n2022-08-12T08:39:21Z leveldb: Delete type=0 #9920\r\n2022-08-12T08:39:21Z leveldb: Generated table #9948@1: 39386 keys, 2174872 bytes\r\n2022-08-12T08:39:21Z leveldb: Generated table #9949@1: 38869 keys, 2171202 bytes\r\n2022-08-12T08:39:22Z leveldb: Generated table #9950@1: 39941 keys, 2173562 bytes\r\n2022-08-12T08:39:22Z leveldb: Generated table #9951@1: 40045 keys, 2148351 bytes\r\n2022-08-12T08:39:22Z leveldb: Compacted 1@1 + 10@2 files => 13010863 bytes\r\n2022-08-12T08:39:22Z leveldb: compacted to: files[ 1 5 54 44 0 0 0 ]\r\n2022-08-12T08:39:22Z leveldb: Delete type=2 #9379\r\n2022-08-12T08:39:22Z leveldb: Delete type=2 #9380\r\n2022-08-12T08:39:22Z leveldb: Delete type=2 #9381\r\n2022-08-12T08:39:22Z leveldb: Delete type=2 #9384\r\n2022-08-12T08:39:22Z leveldb: Delete type=2 #9385\r\n2022-08-12T08:39:22Z leveldb: Delete type=2 #9446\r\n2022-08-12T08:39:22Z leveldb: Delete type=2 #9484\r\n2022-08-12T08:39:22Z leveldb: Delete type=2 #9575\r\n```\r\n\r\n(WRONG!!!)\r\n\r\n```\r\n2022-08-12T08:39:22Z leveldb: Delete type=2 #9606\r\n2022-08-12T08:39:22Z leveldb: Delete type=2 #9820\r\n2022-08-12T08:39:22Z leveldb: Delete type=2 #9929\r\n2022-08-12T08:39:22Z leveldb: Compacting 1@2 + 11@3 files\r\n2022-08-12T08:39:22Z leveldb: Generated table #9952@2: 39561 keys, 2172175 bytes\r\n2022-08-12T08:39:22Z leveldb: Generated table #9953@2: 39511 keys, 2175619 bytes\r\n2022-08-12T08:39:22Z leveldb: Generated table #9954@2: 38783 keys, 2171071 bytes\r\n2022-08-12T08:39:22Z LevelDB read failure: Corruption: block checksum mismatch: G:\\Bitcoin\\chainstate/009775.ldb\r\n```\r\n\r\nNot a \"curruption\": but that file was just DELETED by error (too early)\r\n\r\n```\r\n2022-08-12T08:39:22Z Fatal LevelDB error: Corruption: block checksum mismatch: G:\\Bitcoin\\chainstate/009775.ldb\r\n2022-08-12T08:39:22Z You can use -debug=leveldb to get more complete diagnostic messages\r\n2022-08-12T08:39:22Z Error: Error reading from database, shutting down.\r\n2022-08-12T08:39:22Z Error reading from database: Fatal LevelDB error: Corruption: block checksum mismatch: G:\\Bitcoin\\chainstate/009775.ldb\r\n2022-08-12T08:39:22Z leveldb: Generated table #9955@2: 39035 keys, 2171736 bytes\r\n2022-08-12T08:39:22Z leveldb: Generated table #9956@2: 39537 keys, 2172124 bytes\r\n```\r\n\r\nSo all this depends on the cache fill level and cache sizes. Note that reducing the cache size does not make the deaemon really slower, my filesystem is fast enough (and anyway the chainstate folder lives entirely on a SSD partition (also secured by RAID5) which exhibit no filesystem corruption at all, and no I/O error reported by kernel devices such as SATA adapters, bus handlers, memory managers...\r\n\r\nIt can then happen variably depending on cache size, and one the sped at which adata blocks were downloaded (or not if the could not still be discovered with a source offering them, as advertizeed by their \"headers\", and peers may choose to offer more or less block headers depednign on their capacity).\r\n\r\nNo corruption is ever detected in data blocks (blk*.dat) or their associated reverse indexes (rev*.dat).\r\n\r\nI can run \"-reindex-chainstate\" again and again, I get this error kalways, not just the same chainstate height. All this depends on how the cache is filled in memory (or if there are some entries or not in the mempool, but with a small cache and very early blocks heights, this should never happen). There seems to exist a specific boundary above which the cache \"compacter\" process decides to purge some indexes that it thinks are no longer necessary, but are still needed in later index files The algotithm used seeems to use an \"optimistic heuristic\" that can fail. A deep check is actually not performed.\r\n\r\nLevelDB  does not seem to be the cause of this bug, but it may be incorrectly queried so that the compacter may not find the appropriate index number for a given block height (may be some query can return several rows, and the compacter just considers the first or last row returned by the query, and forgets to process others, thinking that those queries can only return zero or one result; may be caused by a missing aggregation, or selection values not enough selective, e.g. with a \"poor hash\", sometimes producing an unexpected collision in a level-0 index).",
      "created_at" : "2022-08-12T11:35:15Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1213018221",
      "id" : 1213018221,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585ITTBt",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1213018221/reactions"
      },
      "updated_at" : "2022-08-12T11:51:27Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1213018221",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Now it's time to investigate the condition that generated this type of log:\r\n\r\n> 2022-08-12T08:39:22Z leveldb: Delete type=2 #9575\r\n\r\nLevelDB performed very well what it was asked for (during the compaction of the cache in memory), just a few milliseconds before that (now missing) index was required again when Bitcoin resumed is indexing of the chainstate for further blocks with larger heights!\r\n\r\nIt is symptomatic that such crashes are ALWAYS occuring just after a compaction of the chainstate cache. Adn each time I check it, there's no corruption of the data, but the file referenced in the exit logs are always for files that were just deleted within the last second (in fact with extended timestamps in logs, that deletion occured less than 10 milliseconds before, inside the cache compacting which wants to regenerate a new tree of index files while keeping only a few \"old\" indexes that survived multiple passes of compaction).\r\n\r\nNote also that to make the bug reproducible always at the same height in the chainstate, you need to use \"-connect=0\" (nothing will be impacted in the root \"block 0\", no additional headers will be requested for getting new blocks later, something that occurs avery 10 minutes in the live chain), so you must have a safe copy of blocks (blk0*.dat and rev*.dat) generated by letting the deamon run for about 20 minutes until you interrupt it to get a clean backup of these files (it will stop with headers at unpredictable height depending on how fast you could connect to peers).\r\n\r\nThen flush the chainstate completely, and start the daemon once with \"-connect=0 -dbcache=4 -maxmempool=5\" and let it run for some minutes, you can terminate it and it will flush the chainstate to disk with some \"*.ldb files\". You can also checj that blocks files (blk*.dat and rev*.dat) where not touched at all by comparing their content with an archive you made in a \"block2\" directory. Now you can also backup the \"chainstate\" directory to \"chainstate2\".\r\n\r\nBut each time you'll try to the daemon once with \"-connect=0 -dbcache=4 -maxmempool=5\" from the existing chainstate, it will fail with the same height for the same missing index. You can restore that chainstate from \"chainstate2\" to \"chainstate\" (use robocopy no Windows or rsync to make exact mirrors) and relauch it, you'll always get the crash after about hald an hour at most, sometimes sooner (all this depends on when you interrupted the daemon, what was the max height in the main chain of block, or what was the max height of the chainstate, and what was the maixmum size o the dbcache.\r\n\r\nBut with dbcache=4 and maxmumpool=5, you'll get much more frequent calls to the compacter, and you'll finally fall in the \"edge\" case where it incorrectly deleted some indexes that are still needed. LEvelDB has nothing to do with that, filesystem corruption or bad hardware memory have nothing to do with that. It is entirely the internal logic of Bitcoinc Core that produces that, due to a bug in its \"cache compacter\", with incorrect tests.\r\n\r\nAnd you cannot diagnose it in an easily reproducible test if you use the default configuration (the cache is much too large, the compaction occurs too unfrequently and there's too much variation in the chain heights, because of the peers connected and the time you need to find headers and download full blocks. Some existing peers working \"successfully\" have probably NOT used the default configuration, but use extreme values for the dbcache, so that the \"compaction\" of the chainstate never occurs on them. But it's not reasoable at all to have extreme values of dbcache, even if you run it on a machine with 128GB of RAM and very large swaps. There's not even any need to have such extreme size for the performance of the daemon to run a full node, even with the existing rate of transactions in the mempool on the main chain.\r\n",
      "created_at" : "2022-08-12T11:53:59Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1213032600",
      "id" : 1213032600,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585ITWiY",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1213032600/reactions"
      },
      "updated_at" : "2022-08-12T13:40:37Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1213032600",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Also note that you've tagged it for Windows,  even if I have exactly the same when running in WSL, or on a native Linux installation or in a Linux VM running in a Linux hypervisor (like Proxmox).\r\n\r\nThis is not specific to Windows. (even if I first detected it by trying the QT version on Windows, I've since tried to ue the CLI daemon without more success).",
      "created_at" : "2022-08-12T13:37:01Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1213119227",
      "id" : 1213119227,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585ITrr7",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1213119227/reactions"
      },
      "updated_at" : "2022-08-12T13:37:01Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1213119227",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1387035?v=4",
         "events_url" : "https://api.github.com/users/verdy-p/events{/privacy}",
         "followers_url" : "https://api.github.com/users/verdy-p/followers",
         "following_url" : "https://api.github.com/users/verdy-p/following{/other_user}",
         "gists_url" : "https://api.github.com/users/verdy-p/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/verdy-p",
         "id" : 1387035,
         "login" : "verdy-p",
         "node_id" : "MDQ6VXNlcjEzODcwMzU=",
         "organizations_url" : "https://api.github.com/users/verdy-p/orgs",
         "received_events_url" : "https://api.github.com/users/verdy-p/received_events",
         "repos_url" : "https://api.github.com/users/verdy-p/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/verdy-p/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/verdy-p/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/verdy-p"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "So you are claiming this is reproducible on Linux as well as Windows? Surely this can't be with default settings, as I've myself synced tens of nodes on Linux with vanilla settings. And surely there are people who have done it on Windows successfully.\r\n\r\nIt would really help us if you included exact steps to reproduce, starting from a fresh install of the operating system.",
      "created_at" : "2022-08-12T13:43:37Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/25800#issuecomment-1213126463",
      "id" : 1213126463,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25800",
      "node_id" : "IC_kwDOABII585ITtc_",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1213126463/reactions"
      },
      "updated_at" : "2022-08-12T13:43:37Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1213126463",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   }
]
