[
   {
      "body" : "Could you also add the line where the assertion failed (from the python\ntraceback, which should be in the stderr)\n\nOn Fri, Jul 29, 2016 at 10:23 AM, Wladimir J. van der Laan <\nnotifications@github.com> wrote:\n\n> I had this problem once while I was running the walletbackup.py test on\n> 0.13:\n>\n> walletbackup.py:\n> Initializing test directory /tmp/testo3khmc00/37\n> INFO: Generating initial blockchain\n> Assertion failed: 76.69962300 != 50\n> Stopping nodes\n> Not cleaning up dir /tmp/testo3khmc00/37\n> Failed\n>\n> I'm unfortunately unable to reproduce it again, looks like a race\n> condition.\n>\n> Ã¢ÂÂ\n> You are receiving this because you are subscribed to this thread.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/bitcoin/bitcoin/issues/8425>, or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AGGmv60NSH-svLHtS9wi2s23c_U3ZQlBks5qabiRgaJpZM4JX-fm>\n> .\n>\n",
      "created_at" : "2016-07-29T08:51:56Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-236128606",
      "id" : 236128606,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8425",
      "updated_at" : "2016-07-29T08:51:56Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/236128606",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=3",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "body" : "@MarcoFalke done",
      "created_at" : "2016-07-29T08:57:13Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-236129647",
      "id" : 236129647,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8425",
      "updated_at" : "2016-07-29T08:57:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/236129647",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   }
]
