[
   {
      "body" : "Travis failure for `p2p-leaktests.py` unrelated :-)  Is it just me or has the number of spurious Travis failures increased recently?",
      "created_at" : "2017-08-17T14:50:04Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/11076#issuecomment-323096313",
      "id" : 323096313,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11076",
      "updated_at" : "2017-08-17T14:50:04Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/323096313",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/7826565?v=4",
         "events_url" : "https://api.github.com/users/practicalswift/events{/privacy}",
         "followers_url" : "https://api.github.com/users/practicalswift/followers",
         "following_url" : "https://api.github.com/users/practicalswift/following{/other_user}",
         "gists_url" : "https://api.github.com/users/practicalswift/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/practicalswift",
         "id" : 7826565,
         "login" : "practicalswift",
         "organizations_url" : "https://api.github.com/users/practicalswift/orgs",
         "received_events_url" : "https://api.github.com/users/practicalswift/received_events",
         "repos_url" : "https://api.github.com/users/practicalswift/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/practicalswift/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/practicalswift/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/practicalswift"
      }
   },
   {
      "body" : "> Is it just me or has the number of spurious Travis failures increased recently?\r\n\r\n@practicalswift - yes, that's my sense as well. This particular failure is a new test added by me in #11001, but I haven't seen it fail in this way before. It appears that the node doesn't receive a version message that the test framework sends to it, possibly because we're trying to connect too soon after changing the mocktime. I'll see if adding a sleep to the test fixes that.\r\n\r\nI've restarted the job for you.",
      "created_at" : "2017-08-17T15:16:19Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/11076#issuecomment-323103765",
      "id" : 323103765,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11076",
      "updated_at" : "2017-08-17T15:16:19Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/323103765",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/1063656?v=4",
         "events_url" : "https://api.github.com/users/jnewbery/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jnewbery/followers",
         "following_url" : "https://api.github.com/users/jnewbery/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jnewbery/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jnewbery",
         "id" : 1063656,
         "login" : "jnewbery",
         "organizations_url" : "https://api.github.com/users/jnewbery/orgs",
         "received_events_url" : "https://api.github.com/users/jnewbery/received_events",
         "repos_url" : "https://api.github.com/users/jnewbery/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jnewbery/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jnewbery/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jnewbery"
      }
   }
]
