[
   {
      "body" : "Yes, #5677 should fix these kind of issues, it's why I started working on it. rpckeepalive=0 is the workaround until then.",
      "created_at" : "2015-07-17T19:58:30Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6454#issuecomment-122395623",
      "id" : 122395623,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6454",
      "updated_at" : "2015-07-17T19:58:30Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/122395623",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "body" : "I've met the same problem with python bitcoin rpc + bitcoin 0.10.2. Basically my client does this:\r\n- 1 process calls getblock() for a given block and distributes the processing of txs to n subprocesses\r\n- n subprocesses call getrawtransaction() in parallel.\r\n\r\nrpckeepalive=0 fixes the problem with hanging connections but causes another issue, crashing bitcoin after a while.\r\n\r\nTrace found in debug.log\r\n\r\n--------------------------------------------------------------\r\n2015-07-21 23:30:00 LevelDB read failure: IO error: [...]/chainstate/5386207.ldb: The process cannot access the file because it is being used by another process.\r\n\r\n2015-07-21 23:30:00 IO error: [...]/chainstate/5386207.ldb: The process cannot access the file because it is being used by another process.\r\n\r\n--------------------------------------------------------------\r\n\r\nI'm going to decrease the number of subprocesses to check if it's more stable.\r\nThe weird thing is this script has run for a while without any problem. Issues have started a few days ago and are persistent since this date. ",
      "created_at" : "2015-07-22T00:39:51Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6454#issuecomment-123517576",
      "id" : 123517576,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6454",
      "updated_at" : "2015-07-22T00:39:51Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/123517576",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/5204318?v=3",
         "events_url" : "https://api.github.com/users/LaurentMT/events{/privacy}",
         "followers_url" : "https://api.github.com/users/LaurentMT/followers",
         "following_url" : "https://api.github.com/users/LaurentMT/following{/other_user}",
         "gists_url" : "https://api.github.com/users/LaurentMT/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/LaurentMT",
         "id" : 5204318,
         "login" : "LaurentMT",
         "organizations_url" : "https://api.github.com/users/LaurentMT/orgs",
         "received_events_url" : "https://api.github.com/users/LaurentMT/received_events",
         "repos_url" : "https://api.github.com/users/LaurentMT/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/LaurentMT/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/LaurentMT/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/LaurentMT"
      }
   },
   {
      "body" : "The leveldb issue has nothing at all do with this. That's a separate issue, from the error message caused  by another process trying to access the files while bitcoind is running.",
      "created_at" : "2015-07-22T05:23:07Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6454#issuecomment-123565962",
      "id" : 123565962,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6454",
      "updated_at" : "2015-07-22T05:23:07Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/123565962",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=3",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "body" : "@laanwj: thanks for the feedback. Unfortunately, this is the unique trace I've found in the log for the 2 crashes of my bitcoind (Edit: I mean the 2 times).\r\n\r\nFWIW, since my previous comment I've relaunched the task after having decreased the number of subprocesses and moved the bitcoin data directory to a SSD. Everything was ok. \r\n\r\nThe 2 modifications don't help for a diagnostic but I was eager to complete the task which was a bottleneck for my project. I'll try to run the task on another machine in order to reproduce the problem.",
      "created_at" : "2015-07-22T10:35:59Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6454#issuecomment-123658722",
      "id" : 123658722,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6454",
      "updated_at" : "2015-07-22T10:57:33Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/123658722",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/5204318?v=3",
         "events_url" : "https://api.github.com/users/LaurentMT/events{/privacy}",
         "followers_url" : "https://api.github.com/users/LaurentMT/followers",
         "following_url" : "https://api.github.com/users/LaurentMT/following{/other_user}",
         "gists_url" : "https://api.github.com/users/LaurentMT/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/LaurentMT",
         "id" : 5204318,
         "login" : "LaurentMT",
         "organizations_url" : "https://api.github.com/users/LaurentMT/orgs",
         "received_events_url" : "https://api.github.com/users/LaurentMT/received_events",
         "repos_url" : "https://api.github.com/users/LaurentMT/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/LaurentMT/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/LaurentMT/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/LaurentMT"
      }
   },
   {
      "body" : "But do you have another process accessing the database? LevelDB is not\ndesigned for multiprocess operation...\n",
      "created_at" : "2015-07-22T10:38:34Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6454#issuecomment-123659749",
      "id" : 123659749,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6454",
      "updated_at" : "2015-07-22T10:38:34Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/123659749",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=3",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "body" : "@sipa: No other process on my side except the ones calling the rpc api. \r\nMy best guess for now is that it's related to something run by the OS (AV, ...). \r\nI'll have to investigate further others logs of the server.\r\n",
      "created_at" : "2015-07-22T11:05:05Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/6454#issuecomment-123668084",
      "id" : 123668084,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/6454",
      "updated_at" : "2015-07-22T11:05:05Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/123668084",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/5204318?v=3",
         "events_url" : "https://api.github.com/users/LaurentMT/events{/privacy}",
         "followers_url" : "https://api.github.com/users/LaurentMT/followers",
         "following_url" : "https://api.github.com/users/LaurentMT/following{/other_user}",
         "gists_url" : "https://api.github.com/users/LaurentMT/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/LaurentMT",
         "id" : 5204318,
         "login" : "LaurentMT",
         "organizations_url" : "https://api.github.com/users/LaurentMT/orgs",
         "received_events_url" : "https://api.github.com/users/LaurentMT/received_events",
         "repos_url" : "https://api.github.com/users/LaurentMT/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/LaurentMT/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/LaurentMT/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/LaurentMT"
      }
   }
]
