[
   {
      "author_association" : "MEMBER",
      "body" : "I've added a fix for the \"wine: fixed a temporary directory error, please try running the same command again\" issue. It seems that just invoking wine once before wrapping is enough to solve it. This fixes the issue, at least for me locally, when running the Windows CI using `DANGER_RUN_CI_ON_HOST` in a Ubuntu Focal container.",
      "created_at" : "2021-02-09T02:12:10Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/21112#issuecomment-775602612",
      "id" : 775602612,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/21112",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDc3NTYwMjYxMg==",
      "performed_via_github_app" : null,
      "updated_at" : "2021-02-09T02:12:10Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/775602612",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
         "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fanquake/followers",
         "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fanquake",
         "id" : 863730,
         "login" : "fanquake",
         "node_id" : "MDQ6VXNlcjg2MzczMA==",
         "organizations_url" : "https://api.github.com/users/fanquake/orgs",
         "received_events_url" : "https://api.github.com/users/fanquake/received_events",
         "repos_url" : "https://api.github.com/users/fanquake/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fanquake"
      }
   }
]
