[
   {
      "author_association" : "MEMBER",
      "body" : "the failing test seems unrelated. The failure is in `feature_assumevalid.py`, which seems hard to impact from changes that exclusively touch the unit tests, unit test framework, and some comments :) ",
      "created_at" : "2021-02-09T01:54:04Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/21121#issuecomment-775595337",
      "id" : 775595337,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/21121",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDc3NTU5NTMzNw==",
      "performed_via_github_app" : null,
      "updated_at" : "2021-02-09T01:54:04Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/775595337",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1500952?v=4",
         "events_url" : "https://api.github.com/users/amitiuttarwar/events{/privacy}",
         "followers_url" : "https://api.github.com/users/amitiuttarwar/followers",
         "following_url" : "https://api.github.com/users/amitiuttarwar/following{/other_user}",
         "gists_url" : "https://api.github.com/users/amitiuttarwar/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/amitiuttarwar",
         "id" : 1500952,
         "login" : "amitiuttarwar",
         "node_id" : "MDQ6VXNlcjE1MDA5NTI=",
         "organizations_url" : "https://api.github.com/users/amitiuttarwar/orgs",
         "received_events_url" : "https://api.github.com/users/amitiuttarwar/received_events",
         "repos_url" : "https://api.github.com/users/amitiuttarwar/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/amitiuttarwar/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/amitiuttarwar/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/amitiuttarwar"
      }
   }
]
