[
   {
      "body" : "Tried running with timeout changed from 3 to 6, worked fine for 100 runs.\r\nhttps://github.com/bitcoin/bitcoin/blob/master/qa/pull-tester/rpc-tests.py#L268",
      "created_at" : "2016-09-04T23:49:53Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8649#issuecomment-244635689",
      "id" : 244635689,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8649",
      "updated_at" : "2016-09-04T23:49:53Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/244635689",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/7646953?v=3",
         "events_url" : "https://api.github.com/users/yurizhykin/events{/privacy}",
         "followers_url" : "https://api.github.com/users/yurizhykin/followers",
         "following_url" : "https://api.github.com/users/yurizhykin/following{/other_user}",
         "gists_url" : "https://api.github.com/users/yurizhykin/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/yurizhykin",
         "id" : 7646953,
         "login" : "yurizhykin",
         "organizations_url" : "https://api.github.com/users/yurizhykin/orgs",
         "received_events_url" : "https://api.github.com/users/yurizhykin/received_events",
         "repos_url" : "https://api.github.com/users/yurizhykin/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/yurizhykin/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/yurizhykin/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/yurizhykin"
      }
   },
   {
      "body" : "It occurred to me that rather than change the timeout, maybe we could just try to catch that exception and continue, and warn if it happens too much?  I was planning to try that locally and see if that solves my problem.",
      "created_at" : "2016-09-05T00:02:21Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8649#issuecomment-244636266",
      "id" : 244636266,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8649",
      "updated_at" : "2016-09-05T00:02:21Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/244636266",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/7463573?v=3",
         "events_url" : "https://api.github.com/users/sdaftuar/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sdaftuar/followers",
         "following_url" : "https://api.github.com/users/sdaftuar/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sdaftuar/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sdaftuar",
         "id" : 7463573,
         "login" : "sdaftuar",
         "organizations_url" : "https://api.github.com/users/sdaftuar/orgs",
         "received_events_url" : "https://api.github.com/users/sdaftuar/received_events",
         "repos_url" : "https://api.github.com/users/sdaftuar/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sdaftuar/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sdaftuar/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sdaftuar"
      }
   }
]
