[
   {
      "body" : "(FYI this is my jenkins instance that has been seeing this test fail repeatedly over the last couple months.)\r\n\r\nFor some additional color, I timed the RPC calls in wallet-dump.py on a single run on the machine in question -- it happened to pass -- and the first getnewaddress() call took 20 seconds, and the encrypt wallet call took just over 29 seconds.  So the 30 second default timeout is cutting it pretty close.",
      "created_at" : "2016-11-04T00:11:54Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/9077#issuecomment-258311637",
      "id" : 258311637,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/9077",
      "updated_at" : "2016-11-04T00:11:54Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/258311637",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/7463573?v=3",
         "events_url" : "https://api.github.com/users/sdaftuar/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sdaftuar/followers",
         "following_url" : "https://api.github.com/users/sdaftuar/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sdaftuar/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sdaftuar",
         "id" : 7463573,
         "login" : "sdaftuar",
         "organizations_url" : "https://api.github.com/users/sdaftuar/orgs",
         "received_events_url" : "https://api.github.com/users/sdaftuar/received_events",
         "repos_url" : "https://api.github.com/users/sdaftuar/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sdaftuar/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sdaftuar/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sdaftuar"
      }
   }
]
