{
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "The call to CheckBlock() in ConnectBlock() was largely redundant -- the case it tried to protect against was one where we have somehow previously stored an invalid block (eg with different software, presumably).  However, there are other ways that we could get invalid blocks stored on disk, such as if a block was previously accepted (again by different software) that violates rules enforced in ContextualCheckBlock() or ContextualCheckBlockHeader().\r\n\r\nBecause CheckBlock() can return failure due to potential malleability, this call could result in an infinite failure loop, in the event that we have disk corruption and the stored block that we're now trying to connect doesn't match.  Since we're already not catching all forms of corruption between AcceptBlock() and ConnectBlock() (for instance, corruption in a transaction witness), I think we might as well get rid of this call and assume that the corruption will eventually be detected later.\r\n\r\nNote: in the case of a planned soft-fork upgrade, we already need to solve the problem of how to ensure that we don't have invalid blocks stored on disk that might sneak through validation, but that problem is more general than what this invocation of CheckBlock() covers.  I've updated a long comment explaining this issue.",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 0,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12561/comments",
   "created_at" : "2018-02-27T16:40:48Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12561/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/12561",
   "id" : 300705380,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12561/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 12561,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/12561.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/12561",
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/12561.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/12561"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "title" : "Remove call to CheckBlock() in ConnectBlock()",
   "updated_at" : "2018-02-27T16:40:48Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12561",
   "user" : {
      "avatar_url" : "https://avatars0.githubusercontent.com/u/7463573?v=4",
      "events_url" : "https://api.github.com/users/sdaftuar/events{/privacy}",
      "followers_url" : "https://api.github.com/users/sdaftuar/followers",
      "following_url" : "https://api.github.com/users/sdaftuar/following{/other_user}",
      "gists_url" : "https://api.github.com/users/sdaftuar/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/sdaftuar",
      "id" : 7463573,
      "login" : "sdaftuar",
      "organizations_url" : "https://api.github.com/users/sdaftuar/orgs",
      "received_events_url" : "https://api.github.com/users/sdaftuar/received_events",
      "repos_url" : "https://api.github.com/users/sdaftuar/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/sdaftuar/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/sdaftuar/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/sdaftuar"
   }
}
