[
   {
      "body" : "The problem persists even after re-starting the client and doing a -rescan.\r\n\r\nI was connected only via Tor while testing this, so could it be that my mined block was not broadcasted or via too less nodes (I'm no pro on that part of Bitcoin, sorry if this makes no sense)?",
      "created_at" : "2012-10-22T07:22:37Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/1946#issuecomment-9654571",
      "id" : 9654571,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1946",
      "updated_at" : "2012-10-22T11:14:03Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/9654571",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1419649?v=3",
         "events_url" : "https://api.github.com/users/Diapolo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/Diapolo/followers",
         "following_url" : "https://api.github.com/users/Diapolo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/Diapolo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/Diapolo",
         "id" : 1419649,
         "login" : "Diapolo",
         "organizations_url" : "https://api.github.com/users/Diapolo/orgs",
         "received_events_url" : "https://api.github.com/users/Diapolo/received_events",
         "repos_url" : "https://api.github.com/users/Diapolo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/Diapolo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/Diapolo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/Diapolo"
      }
   },
   {
      "body" : "In addition I was now able to reproduce the following error with the same test condition as described above:\r\n![assertion problem](http://i47.tinypic.com/2py9hxf.png)",
      "created_at" : "2012-10-22T08:21:13Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/1946#issuecomment-9655859",
      "id" : 9655859,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1946",
      "updated_at" : "2012-10-22T08:21:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/9655859",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1419649?v=3",
         "events_url" : "https://api.github.com/users/Diapolo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/Diapolo/followers",
         "following_url" : "https://api.github.com/users/Diapolo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/Diapolo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/Diapolo",
         "id" : 1419649,
         "login" : "Diapolo",
         "organizations_url" : "https://api.github.com/users/Diapolo/orgs",
         "received_events_url" : "https://api.github.com/users/Diapolo/received_events",
         "repos_url" : "https://api.github.com/users/Diapolo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/Diapolo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/Diapolo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/Diapolo"
      }
   },
   {
      "body" : "Can you try moving the line 'CBlockIndex* pindexPrev = pindexBest;'  in CreateNewBlock to inside the large block that is headed by 'LOCK2(cs_main, mempool.cs);' (right below that LOCK2)",
      "created_at" : "2012-10-22T10:54:28Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/1946#issuecomment-9659573",
      "id" : 9659573,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1946",
      "updated_at" : "2012-10-22T10:55:41Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/9659573",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=3",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "body" : "Yes, I'll try again with the above applied.",
      "created_at" : "2012-10-22T11:02:47Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/1946#issuecomment-9659749",
      "id" : 9659749,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1946",
      "updated_at" : "2012-10-22T11:02:47Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/9659749",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1419649?v=3",
         "events_url" : "https://api.github.com/users/Diapolo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/Diapolo/followers",
         "following_url" : "https://api.github.com/users/Diapolo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/Diapolo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/Diapolo",
         "id" : 1419649,
         "login" : "Diapolo",
         "organizations_url" : "https://api.github.com/users/Diapolo/orgs",
         "received_events_url" : "https://api.github.com/users/Diapolo/received_events",
         "repos_url" : "https://api.github.com/users/Diapolo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/Diapolo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/Diapolo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/Diapolo"
      }
   },
   {
      "body" : "I was still able to get the ``Warning: Displayed transactions may not be correct! You may need to upgrade, or other nodes may need to upgrade.`` message, an assertion did not occur anymore ... but I need more time testing this.\r\n\r\nNot sure if that message is related to Ultraprune, perhaps I'll take the official 0.7.1 client an fire up the same test scenario.",
      "created_at" : "2012-10-22T13:17:34Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/1946#issuecomment-9663172",
      "id" : 9663172,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1946",
      "updated_at" : "2012-10-22T13:17:34Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/9663172",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1419649?v=3",
         "events_url" : "https://api.github.com/users/Diapolo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/Diapolo/followers",
         "following_url" : "https://api.github.com/users/Diapolo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/Diapolo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/Diapolo",
         "id" : 1419649,
         "login" : "Diapolo",
         "organizations_url" : "https://api.github.com/users/Diapolo/orgs",
         "received_events_url" : "https://api.github.com/users/Diapolo/received_events",
         "repos_url" : "https://api.github.com/users/Diapolo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/Diapolo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/Diapolo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/Diapolo"
      }
   },
   {
      "body" : "When connecting a block fails, its work amount is written as bad. When this happens because of an wrong reason, you should restart with a clean datadir, as the warning will remain (until the chain catches up at least).",
      "created_at" : "2012-10-22T13:24:54Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/1946#issuecomment-9663392",
      "id" : 9663392,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1946",
      "updated_at" : "2012-10-22T13:24:54Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/9663392",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=3",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "body" : "Actually, you shouldn't be able to mine at all during IBD. I'm sure this bug existed before ultraprune, but the resulting assertion failure is probably new.",
      "created_at" : "2012-10-22T13:29:39Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/1946#issuecomment-9663564",
      "id" : 9663564,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1946",
      "updated_at" : "2012-10-22T13:29:39Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/9663564",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=3",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "body" : "@sipa\r\nWhat do you think about adding this into the setgenerate RPC call?\r\n\r\n<pre>\r\n    if (vNodes.empty())\r\n        throw JSONRPCError(RPC_CLIENT_NOT_CONNECTED, \"Bitcoin is not connected!\");\r\n    \r\n    if (IsInitialBlockDownload())\r\n        throw JSONRPCError(RPC_CLIENT_IN_INITIAL_DOWNLOAD, \"Bitcoin is downloading blocks...\");\r\n</pre>\r\n\r\nThis check is also uses IN the threads itself, but when adding this to the RPC command we prevent spawning 4 threads that just idle and perhaps even prevent block-generation happening in some other weird situations (that currently happen, because I was able to mine a block while beeing on IBD), which causes further problems.\r\n\r\nSo start the mining threads for RPC call only when connected and not in IBD (explicit usage) and still alow the old behavior, when using -gen (as you most likely want to start mining, when the client is ready here - implicit usage).\r\n\r\nI was not able to reproduce the assertion again, so your idea seems to have fixed that one! You think it was a locking problem?\r\n\r\nEdit: Do you thing it makes sense to create a pull for your assert fix here or is that obsolete with your last patches to master?",
      "created_at" : "2012-10-22T14:07:07Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/1946#issuecomment-9664839",
      "id" : 9664839,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/1946",
      "updated_at" : "2012-10-23T06:29:28Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/9664839",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1419649?v=3",
         "events_url" : "https://api.github.com/users/Diapolo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/Diapolo/followers",
         "following_url" : "https://api.github.com/users/Diapolo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/Diapolo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/Diapolo",
         "id" : 1419649,
         "login" : "Diapolo",
         "organizations_url" : "https://api.github.com/users/Diapolo/orgs",
         "received_events_url" : "https://api.github.com/users/Diapolo/received_events",
         "repos_url" : "https://api.github.com/users/Diapolo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/Diapolo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/Diapolo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/Diapolo"
      }
   }
]
